dotnet/csharplang

- README.md
- proposals/README.md
Updated the README.md files for consitency between the C# and VB repos.
> Consitency updates between C# and VB repos.

- README.md
> Corrected notes link to point to meetings folder.

- .gitattributes
This change ensures various Git clients on different operating systems
will commit changes to the text files in this repository uniformly.
> Add initial .gitattributes

- proposals/auto-prop-field-attrs.md
Proposal specification for field-targeting attributes for auto-implemented properties.
> Create auto-prop field attributes proposal specification

- proposals/intptr-operators.md
> Adding the intptr-operators proposal.

- meetings/2016/README.md
- meetings/2017/README.md
> Add README for 2017, update 2016 README.

- proposals/intptr-operators.md
> Updating the `intptr-operators` proposal to include the list of operators.

- proposals/async-main.md
Contributes to https://github.com/dotnet/csharplang/issues/97
> Add proposal for Async Main

- proposals/patterns.md
> Update the spec for handling constant patterns (implementation in progress)

- proposals/conditional-ref.md
Proposal for the   "conditional ref expression" feature.
moved from https://github.com/dotnet/roslyn/issues/16473
Related to: https://github.com/dotnet/csharplang/issues/223
> Proposal for the   "conditional ref expression" feature

- proposals/target-typed-default.md
This is the initial target-typed "default" proposal tracked by https://github.com/dotnet/csharplang/issues/102
CC @dotnet/csharplangdesign
> Initial target-typed "default" proposal

- proposals/improved-common-type.md
@MadsTorgersen Feedback welcome. I think this is suitable for LDM review.
/cc @dotnet/csharplangdesign
> Add proposed C# spec edits for improved common type.

- proposals/csharp-7.1/infer-tuple-names.md
This is the proposal document for championed issue https://github.com/dotnet/csharplang/issues/415
@gafter @MadsTorgersen  @dotnet/roslyn-compiler for review.
> Proposal document for infer tuple names

- Language-Version-History.md
- README.md
> Add language version history.

- proposals/caller-argument-expression.md
This is the official proposal for https://github.com/dotnet/csharplang/issues/205, which was championed in https://github.com/dotnet/csharplang/issues/287.
/cc @gafter, @tannergooding, @HaloFour
> Add proposal for CallerArgumentExpression attribute

- proposals/default-interface-methods.md
> Move some open and closed issues into default-interface-methods.md

- proposals/readonly-ref.md
cc @VSadov @tmat @dotnet/roslyn-compiler
> Updated syntax and metadata sections of ref-readonly proposal

- proposals/readonly-ref.md
cc @MadsTorgersen @VSadov @jaredpar
> Note on spec 7.5.3.1 violation

- proposals/readonly-ref.md
Please review if my assumption in this change is incorrect.
> Corrected typo in feature summary

- proposals/async-streams.md
This is by no means a finished design; rather, it's a starting point for subsequent discussions, design, and prototyping.
Contributes to #43
cc: @MadsTorgersen
> Add strawman proposal for async iterators

- proposals/async-streams.md
> Update async stream proposal based on design meeting

- proposals/readonly-ref.md
The code samples were all indented 8 spaces on the left, which make them slightly harder to read. This PR fixes that.
> Indent code samples in readonly-ref.md

- proposals/fixed-sized-buffers.md
> Adding the 'fixed-sized-buffers' proposal.

- proposals/csharp-7.2/span-safety.md
We no longer assume that ` Span<T> span = new Span<T>(ref variable); ` can actually "wrap" the reference to the variable.
This allows to relax some of the safety requirements.
> Update span-safety rules to account for recent changes

- proposals/declaration-expressions.md
Direct link to readable doc: https://github.com/dotnet/csharplang/pull/977/files?short_path=9ee3b9d#diff-9ee3b9d686b057ca42683cf843811bc5
> Add declaration-expressions.md proposal

- proposals/caller-argument-expression.md
See https://github.com/dotnet/csharplang/commit/7d6fe57574f8dce80b62c82d0f75acb3e98f4556#commitcomment-22897524. @jnm2 unintentionally corrected an intentional typo.
/cc @jnm2, @gafter
> Fix changes from #537

- spec/lexical-structure.md
Just fixed a word "contectual" to "contextual"
> Corretion of word

- proposals/pattern-based-fixed.md
Defining a pattern that would allow types to participate in fixed statements.
LDM https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-12-04.md discussed this
> Proposal for the Pattern based fixed statement

- Language-Version-History.md
> Add C# 7.3 to language history

- proposals/csharp-8.0/ranges.md
- proposals/ranges.md
cc @VSadov @jaredpar 
cc @dotnet/roslyn-compiler @dotnet/csharplangdesign
> Added ranges proposal

- proposals/csharp-7.3/auto-prop-field-attrs.md
- proposals/csharp-7.3/blittable.md
- proposals/csharp-7.3/expression-variables-in-initializers.md
- proposals/csharp-7.3/improved-overload-candidates.md
- proposals/csharp-7.3/pattern-based-fixed.md
- proposals/csharp-7.3/stackalloc-array-initializers.md
FYI @gafter 
Relates to https://github.com/dotnet/csharplang/issues/1516
> Remove unnecessary checkboxes from 7.3 speclets

- proposals/csharp-7.3/pattern-based-fixed.md
@vsadov @OmarTawfik  @gafter @jaredpar FYI
> The method name is `GetPinnableReference`

- proposals/readonly-instance-members.md
FYI. @jaredpar who is championing the proposal
> Adding the readonly-methods proposal document.

- spec/namespaces.md
> Fix brace | add semicolon

- proposals/csharp-7.3/blittable.md
We use Allman style braces, where each brace begins on a new line. 
See: [coding-style.md](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md )
> Code Formatted

- Communities.md
Includes links to major C# communities.
> Add a communities document

- proposals/nullable-reference-types-specification.md
> Add NRT spec

- spec/documentation-comments.md
- changed link to https
- changed ie to that is
> minor fixes

- proposals/null-arg-checking.md
This is a proposal that was discussed by LDM on 2019/1/14. Will link to LDM notes when they're available.
Note: sorry for getting this out same day as LDM meeting. It's a small proposal, got tied up last week and didn't finish writing until shortly before our LDM meeting.
> Proposal: Simplified parameter null validation

- proposals/function-pointers.md
This updates the function pointer proposal based on previous LDM meetings and PR feedback. 
Note: i'm merging this immediately so the proposal is updated for an LDM meeting later today. Please do though continue to leave feedback. I will incorporate it and feedback from the LDM meeting today in a later update of the proposal.
> Function pointer updates

- Language-Version-History.md
Updaate the language history with information about C# 1.2. Minor
release and no there was not a 1.1.
> C# 1.2 notes

- spec/expressions.md
first table entry should be empty
> fix floating-point subtraction table

- proposals/caller-argument-expression.md
- proposals/covariant-returns.md
- proposals/declaration-expressions.md
- proposals/default-interface-methods.md
- proposals/fixed-sized-buffers.md
As @BillWagner is starting to publish the proposals, I saw some Markdown and linting issues that could be fixed. Breaking this down in several PRs for easier review.
> markdown fixes - part 1

- proposals/csharp-7.2/conditional-ref.md
Add an H1
Fix the horizontal rule tag.
Found while working on dotnet/docs#11121
> markdown syntax updates

- proposals/intptr-operators.md
- proposals/lambda-attributes.md
- proposals/null-conditional-await.md
- proposals/readonly-instance-members.md
- proposals/readonly-locals.md
I did rename readonly-locals from using underscore to dash here 
/cc @BillWagner @jcouv
> markdown fixes - part 2

- proposals/csharp-7.0/pattern-matching.md
the 'proposals' folder should not be included.
> fix one bad link.

- proposals/index-range-changes.md
This is a set of proposed changes to the `Index` and `Range` features based on customer feedback.
Note: when looking at the LDM notes from 4/1 the version of the proposal being discussed is captured [here](https://github.com/dotnet/csharplang/pull/2397/commits/8dd672612693932d86a4d065554bf4f97ac4a23e). The PR in it's current state reflects the changes requested by LDM team
> Proposed changes to Index / Range

- proposals/index-range-changes.md
This duplicate sentence was missed when #2397 got merged (/cc @jaredpar).
> Fix duplicate part from suggestion

- spec/introduction.md
> Fix incorrect var named in the introduction

- proposals/csharp-8.0/async-streams.md
> Document [EnumeratorCancellation] attribute

- spec/classes.md
Fix https://github.com/dotnet/docs.zh-cn/issues/473
> Add missing type name

- spec/introduction.md
> Added missing code tag as pointed out in #2371

- proposals/function-pointers.md
@jkotas @jaredpar for review. Addressed offline comments.
> Updates to the function pointers spec.

- meetings/2019/LDM-2019-05-15.md
Tagging @jskeet 
Tagging @MadsTorgersen @agocke since updating the LDM notes to clarify.
Relates to https://github.com/dotnet/roslyn/issues/37544
> Refined description for NotNull attribute

- proposals/csharp-7.2/span-safety.md
Include same samples and explanations for why several of the `Span<T>`
and `ref struct` rules exist.
> Span safety samples

- Language-Version-History.md
> Fix VS version

- proposals/static-lambdas.md
Championed issue https://github.com/dotnet/csharplang/issues/275
Relates to PR https://github.com/dotnet/roslyn/pull/39121
> Proposed speclet for static lambdas

- proposals/csharp-8.0/nullable-reference-types-specification.md
> Remove mentions of safeonly context

- proposals/csharp-8.0/nested-stackalloc.md
@MadsTorgersen @dotnet/roslyn-compiler Could I please get some eyes on this?
> Add spec for nested stackalloc

- proposals/csharp-8.0/nullable-reference-types-specification.md
From decision in LDM https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-12-18.md#var
> var infers a nullable type

- Language-Version-History.md
https://stackoverflow.com/questions/12112881/has-foreachs-use-of-variables-been-changed-in-c-sharp-5
> breaking changes  foreach loop c# 5

- spec/types.md
Test markdown fixes per https://ceapex.visualstudio.com/CPS/_workitems/edit/166961
> Csharp5 standard

- spec/structs.md
- spec/types.md
- spec/unsafe-code.md
- spec/variables.md
Per https://ceapex.visualstudio.com/CPS/_workitems/edit/169416
@BillWagner please review and let me know if I can refine this further. Thanks!
> Csharp5 Standard Markdown Fixes (Struts)

- proposals/csharp-7.0/tuples.md
In this PR, I address the feedback left on dotnet/csharplang#3031 where the change to make was obvious. (Other items will be logged as issues).
> Tuples feedback

- proposals/csharp-8.0/async-streams.md
> Fix a grammar issue

- proposals/csharp-8.0/readonly-instance-members.md
Fixes dotnet/docs#13841
I added a note (first recommendation) but did not make any additions for the second. That's covered in more of the tutorials and conceptual docs.
> clarify readonly set

- proposals/csharp-7.0/ref-locals-returns.md
- proposals/csharp-7.0/value-task.md
@BillWagner @jaredpar @MadsTorgersen FYI
> Add placeholder specs for two features from C# 7.0

- proposals/target-typed-new.md
> Clean up the specification portion of target-typed new

- proposals/csharp-8.0/nullable-reference-types.md
Addresses: https://github.com/dotnet/docs/issues/14491
> Added details and examples for null guard guidance

- proposals/csharp-8.0/nullable-reference-types-specification.md
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/nullable-reference-types-specification
> Typo "*** This ～ incomplete. ***"→"***This ～ incomplete.***"

- proposals/constant_interpolated_strings.md
Add proposal spec for constant interpolated strings
> Add constant interpolated strings

- proposals/records.md
Update spec section on "Equality members" based on LDM 2020-06-15 discussion and subsequent "working group" proposal.
> Records: update "Equality members" spec section

- proposals/csharp-8.0/ranges.md
Fixes https://github.com/dotnet/docs/issues/18812
> Update the ranges.md file to correctly represent the actual impl.

- proposals/pointer-null-coalescing.md
This proposal is linked with championed issue #418
> Proposal for supporting pointer types in null coalescing operators

- proposals/repeat-attributes.md
- proposals/repeated-attributes.md
Adds proposal for the "repeated attributes" feature.
> Repeated attributes across partial declarations

- proposals/init.md
Fixes https://github.com/dotnet/roslyn/issues/44704
> Local functions and lambdas are outside init phase

- proposals/records.md
Here's the general section of the spec on method parameters, for context: https://github.com/dotnet/csharplang/blob/master/spec/classes.md#method-parameters (note it doesn't have `in` yet)
> Disallow certain modifiers in record parameters

- proposals/csharp-9.0/records.md
@dotnet/roslyn-compiler for review.
> Clarify some restrictions on records

- proposals/csharp-9.0/records.md
See https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-07-27.md#conclusion-1
> Specify equality operators for records

- meetings/2020/LDM-2020-08-24.md
> Fix typo in LDM-2020-08-24.md

- proposals/csharp-9.0/records.md
Based on the changes requested in https://github.com/dotnet/roslyn/pull/47515
> Update records spec

- proposals/csharp-9.0/native-integers.md
Replaces https://github.com/dotnet/csharplang/pull/3938
> Update native integers conversions

- proposals/csharp-9.0/records.md
> System.StringBuilder -> System.Text.StringBuilder

- proposals/discriminated-unions.md
Changed "data class" in examples to "record" and some other adjustments to conform more with records.
Also swapped position of "partial" and "abstract" because apparently the compiler only likes it the other way.
To get the examples to compile the classes that contain the records ("Shape", "Binary" and "Expr") should also be changed to record but I left that out for now.
> Updated records in proposal "discriminated-unions"

- proposals/csharp-9.0/unconstrained-type-parameter-annotations.md
Proposal for annotations on unconstrained type parameters: `T?` and `where T : default`
> Add proposals/csharp-9.0/unconstrained-type-parameter-annotations.md

- proposals/csharp-9.0/nullable-reference-types-specification.md
> Fork NRT speclet

- proposals/csharp-7.0/task-types.md
Moving the task-like proposal from roslyn to csharplang
https://github.com/dotnet/roslyn/blob/master/docs/features/task-types.md
> Move task like proposal to csharplang

- proposals/csharp-9.0/nullable-reference-types-specification.md
This is a first pass.
Several things aren't yet covered:
- invocations and arguments (including `ref` and `out` ),
- attributes,
- type substitution rules,
- difference between "maybe null" and "maybe default", 
- array syntax, 
- warnings for overrides, implementations, and delegate conversions,
- null tests, pure null tests, and learning from them,
- special methods (`CompareExchange`),
- conversions (including user-defined conversions),
- property/indexer input versus output,
- and more (feel free to comment with area that we should expand).
Tagging @MadsTorgersen @jaredpar
> Refresh NRT spec

- proposals/csharp-9.0/function-pointers.md
> Fix minor error in proposal that affects docs

- proposals/csharp-9.0/records.md
- proposals/record-structs.md
Corresponding LDM notes: https://github.com/dotnet/csharplang/blob/master/meetings/2021/LDM-2021-01-27.md
FYI @dotnet/roslyn-compiler
> Record decisions for record structs

- proposals/csharp-9.0/records.md
- proposals/improved-definite-assignment.md
> Update conditional expression section of IDA

- proposals/required-members.md
This is the initial required properties proposal discussed today, modulo some clarifications and adding more open questions. I'd like to get this checked in, then we can start working through open questions in future LDMs.
> Add initial required properties proposal

- proposals/record-structs.md
FYI @AlekseyTs @dotnet/roslyn-compiler 
Relates to PR https://github.com/dotnet/roslyn/pull/51720
> Remove mention of "copy constructor"

- proposals/record-structs.md
> Add open question on GetHashCode

- proposals/extended-property-patterns.md
Championed issue: https://github.com/dotnet/csharplang/issues/4394
Prototype: https://github.com/dotnet/roslyn/pull/52139
Proposal: [Rendered](https://github.com/alrz/csharplang/blob/patch-3/proposals/extended-property-patterns.md)
> Add extended-property-patterns.md

- proposals/async-method-builders.md
> Use AsyncMethodBuilder and remove scoped scenarios

- proposals/improved-interpolated-strings.md
Updates the proposal with feedback from API review and previous LDM sessions.
> Update interpolated string proposal

- proposals/lambda-improvements.md
Update proposal based on recent discussions.
> Update lambda improvements proposal

- proposals/csharp-9.0/records.md
- proposals/record-structs.md
Spec change for:
- https://github.com/dotnet/roslyn/pull/52660 (hidden positional members)
- https://github.com/dotnet/roslyn/pull/52480 (positional fields)
Tagging @AlekseyTs @RikkiGibson
> Update docs for positional fields and hidden positional members

- proposals/improved-interpolated-strings.md
This updates the interpolated string proposal with the latest ldm feedback, and gets it ready for the remaining open questions to be asked tomorrow.
> Rework improved interpolated string builder proposal with LDM feedback.

- proposals/parameterless-struct-constructors.md
Updates based on recent discussions.
> Update parameterless struct constructor proposal

- meetings/2021/LDM-2021-05-17.md
> Typo and rendering fixes

- proposals/list-patterns-enumerables.md
- proposals/list-patterns.md
This is mostly a refactoring, with minor edits for readability.
FYI @alrz
> Split list patterns on enumerables

- proposals/improved-interpolated-strings.md
Updates the spec to reflect the naming changes, the change in Create vs ctor, and the other open questions that have since been resolved.
@chsienki @AlekseyTs @stephentoub for review.
> Update the interpolated string handler spec

- Language-Version-History.md
Should probably link to [csharp-7.0/pattern-matching.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-7.0/pattern-matching.md)
> pattern 404 link

- proposals/async-method-builders.md
Test plan: https://github.com/dotnet/roslyn/issues/51999
Implementation: https://github.com/dotnet/roslyn/pull/54033
> Update spec to reflect LDM 2021/06/21 decisions

- Language-Version-History.md
@BillWagner @dotnet/roslyn-compiler for review.
> Add C# 10 to language history

- meetings/2021/README.md
Will add a write-up of the situation and the potential solutions in advance of the meeting.
> Add partial base type nullability differences agenda item

- spec/conversions.md
See dotnet/docs#26006
Also fixed in dotnet/csharpstandard#371
> Add missing semicolon

- proposals/csharp-9.0/nullable-reference-types-specification.md
> Remove new handling of nullable value types in method type argument inference

- proposals/csharp-10.0/improved-interpolated-strings.md
Fixed a couple of small issues inthe initial paragraph that were incorrectly worded.
> Update the interpolated string spec

- proposals/params-span.md
Champion issue: https://github.com/dotnet/csharplang/issues/1757
> Add proposal for `params Span<T>`

- proposals/semi-auto-properties.md
> Spec change around backing field being readonly

- proposals/semi-auto-properties.md
Addresses https://github.com/dotnet/csharplang/pull/5575#issuecomment-1001714937
cc @RikkiGibson @AlekseyTs @333fred @CyrusNajmabadi  @jnm2
> Update semi auto props spec around readonly backing field for init-only

- proposals/semi-auto-properties.md
@CyrusNajmabadi Is it clearer now?
> Tweak readonly backing field wording

- proposals/low-level-struct-improvements.md
Move from hard wrapping to soft wrapping which is more common in our
proposals.
In the process of editting this doc, wanted to submit the formatting
change separately to make the upcoming proposals changes easier to
review
> Fix line wrapping

- proposals/csharp-10.0/parameterless-struct-constructors.md
Update parameterless-struct-constructors.md based on [LDM decision](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-01-03.md#parameterless-struct-constructors-revisited) to not synthesize a parameterless `struct` constructor and report an error if a `struct` contains field initializers and no constructors.
> Never synthesize parameterless struct constructor

- proposals/required-members.md
Updating the required members spec with feedback from the most recent 2 LDM meetings on the feature.
> Update required members spec

- proposals/csharp-10.0/record-structs.md
> Fix typo in record-structs.md

- Language-Version-History.md
added `With expression for anonymous type` for C# 10
> Record details on `with` for structs and anonymous types

- proposals/checked-user-defined-operators.md
https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-02-09.md
https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-02-14.md
> Update checked-user-defined-operators.md according to LDM decisions

- proposals/semi-auto-properties.md
The open question being updated by this PR is on the agenda for Wednesday: https://github.com/dotnet/csharplang/blob/main/meetings/2022/README.md#mar-2-2022
Requested at https://discord.com/channels/732297728826277939/732297994699014164/947231091251621948
> Provide more information on open question 2 on the field keyword

- proposals/csharp-9.0/native-integers.md
Updates to proposals/csharp-9.0/native-integers.md from suggestions in https://github.com/dotnet/docs/issues/28539.
> Updates to native-sized integers proposal

- proposals/csharp-8.0/default-interface-methods.md
Fixes https://github.com/dotnet/docs/issues/26115. @AlekseyTs for review.
> Remove incorrect `override` keywords

- proposals/low-level-struct-improvements.md
Clarification on a few points based on feedback from implementation
https://github.com/dotnet/roslyn/pull/60416
> Ref fields updates

- proposals/required-members.md
A couple of small updates to required members from LDM.
> Updates to required members

- meetings/2022/LDM-2022-02-09.md
hte -> the
targetting -> targeting
> Fix typo in LDM-2022-02-09.md

- proposals/low-level-struct-improvements.md
Updates based on discussions and LDM meeting
> Ref fields update

- proposals/low-level-struct-improvements.md
This PR has two changes:
1. Moving compat considerations into considerations section. 
2. Detail how restricted types will be removed from the compiler
> Update ref fields for restricted types

- meetings/2020/LDM-2020-06-22.md
The list was formatted as code (and not numbered correctly).
> Fixed formatting of a list

- proposals/low-level-struct-improvements.md
Clarified wording for a couple of rules, and fixed a couple of links.
> Minor updates to ref fields proposal

- proposals/required-members.md
Update the required members spec with LDM decisions and minor implementation details as needed.
> Update required members

- proposals/csharp-10.0/improved-definite-assignment.md
Deleted the deprecated target.
> [BrokenLinksH2] Fixed the link path

- meetings/2022/LDM-2022-01-12.md
non-existant -> non-existent
targetting -> targeting
> Fix typo in LDM-2022-01-12.md

- proposals/low-level-struct-improvements.md
Put all the examples for the rules into a single place
> Re-organize doc

- meetings/2021/LDM-2021-06-07.md
> Fix typo in LDM-2021-06-07.md

- proposals/low-level-struct-improvements.md
Changed warning to diagnostic, and fixed a couple of typos.
> Minor updates to ref fields spec

- proposals/csharp-8.0/default-interface-methods.md
Confirmed intention of sample code with Bill Wagner on Twitter
> Correct sample code for explicit implementation

- meetings/2022/README.md
Sorry for that, my bad not reading the spec carefully.
> Remove #6089 from schedule

- meetings/2022/LDM-2022-07-27.md
> Fix typo in LDM-2022-07-27.md

- proposals/numeric-intptr.md
> Mention NumerIntPtr feature flag

- proposals/low-level-struct-improvements.md
Decided re-assign is not a word but reassign is. Fixed up the doc
> Fix reassign spelling error

- proposals/csharp-11.0/file-local-types.md
@jcouv
Related to dotnet/roslyn#60819
> Disallow global using static with file types

- proposals/pattern-variables.md
Also allow between conditions of an `if/else`.
FYI @alrz @333fred
> Allow types to differ in terms of nullability

- proposals/csharp-11.0/low-level-struct-improvements.md
I found it hard to look up the right parts of the doc. This should help.
> Add sub-section headers

- proposals/csharp-11.0/required-members.md
Fixed typo as requested in issue dotnet/docs#33335
> Fixed minor typo in required-members.md

- proposals/csharp-10.0/enhanced-line-directives.md
Fixes dotnet/docs#33666
edit by @BillWagner to add referenced issue.
> Update formatting of line directive expression

- meetings/working-groups/roles/roles-2022-11-10.md
Fix typo: modopt approach allows overload
FYI @333fred
> Fix typo: modopt approach allows overload

- meetings/working-groups/roles/roles-2023-01-23.md
FYI @333fred @AlekseyTs @MadsTorgersen @captainsafia @KathleenDollard
> Public roles WG notes for 2023-01-23

- meetings/working-groups/roles/roles-2023-01-25.md
FYI @333fred @AlekseyTs @MadsTorgersen @captainsafia
> Publish notes for roles WG 2023-01-25

- proposals/csharp-9.0/records.md
I think these are two little typos.
> Fix incorrect C# syntax

- proposals/collection-literals.md
Content copied verbatim from #5354.
After adding this document, the proposal text in #5354 (after the Summary and Motivation) will be **removed and replaced with a message** that links to this document:
> _The content of the proposal has moved to [proposals/collection-literals.md](https://github.com/dotnet/csharplang/blob/main/proposals/collection-literals.md). Further updates to the proposal should be made there._
> Create proposals/collection-literals.md from proposal in #5354

- proposals/collection-literals.md
> Minor corrections to collection-literals.md

- proposals/primary-constructors.md
> Remove status section from primary constructors speclet

- proposals/csharp-11.0/static-abstracts-in-interfaces.md
Found that checklist in [documentation](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/static-abstracts-in-interfaces). I don't think it should be there.
> Update implemented proposal checklist

- proposals/using-alias-types.md
Only one H1 per article is allowed on docs.
> Remove extra H1

- proposals/collection-literals.md
Split dictionaries out to a separate section; minor formatting changes.
> Updates to collection-literals.md

- proposals/primary-constructors.md
> fix code snippet

- proposals/collection-literals.md
Describe the types to which a collection literal expression can be implicitly converted.
> Collection literal conversions

- meetings/working-groups/roles/extensions-wg-2023-06-07.md
FYI @AlekseyTs @MadsTorgersen @333fred 
> Publish notes for extensions WG 2023-06-07

- proposals/collection-literals.md
Update section for custom create methods based on recent discussions.
> Collection literals: create methods

- proposals/ref-readonly-parameters.md
Relates to test plan: https://github.com/dotnet/roslyn/issues/68056
> Clarify where `[RequiresLocation]` is an error

- proposals/collection-expressions.md
@cston @CyrusNajmabadi for review. This is not a complete rename (I only changed the name of the file, title and first paragraph), but that's sufficient for now (for purpose of linking for announcement).
> Rename to "collection expressions"

- proposals/collection-expressions.md
Update *create method* section; remove *extension method invocation*.
> Collection expressions: updates for builder methods

- meetings/2023/README.md
@jaredpar @KathleenDollard @jjonescz
> Add `ref readonly parameters` to agenda

- proposals/collection-expressions-next.md
- proposals/csharp-12.0/collection-expressions.md
Remove natural type and dictionaries from C#12 proposal.
> Collection expressions: limit proposal to C#12 only

- meetings/2023/README.md
- meetings/working-groups/collection-literals/CL-LDM-2023-08-14.md
Update on collection expressions for LDM 2023-08-14.
> Collections expressions: LDM update

- proposals/csharp-12.0/collection-expressions.md
> missed one anchor

- proposals/csharp-11.0/low-level-struct-improvements.md
Had a question from a customer sample today that I wanted to make more explicit in the annotation discussion.
> ref rule cleanup

- proposals/csharp-12.0/collection-expressions.md
Allow conversion to nullable value type targets.
> Collection expressions: nullable value type targets

- proposals/csharp-12.0/collection-expressions.md
See https://github.com/dotnet/roslyn/pull/69852#discussion_r1320224745
> Collection expressions: include additional implicit conversions

- proposals/csharp-12.0/collection-expressions.md
Describe evaluation order and methods used in collection instance construction.
> Collection expressions: construction

- proposals/csharp-12.0/using-alias-types.md
@KathleenDollard @CyrusNajmabadi for review. Thanks
> Mention nullability annotations

- proposals/csharp-12.0/using-alias-types.md
@RikkiGibson @KathleenDollard @CyrusNajmabadi for review.
> Fix nullability rule

- proposals/csharp-12.0/inline-arrays.md
There is no anonymous inline array syntax.
> Remove invalid collection literal examples

- proposals/csharp-12.0/collection-expressions.md
Updates following [LDM-2024-01-10](https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-01-10.md).
> Collection expressions: require applicable constructor and Add method for target type implementing IEnumerable

- meetings/working-groups/collection-literals/CL-2024-01-23.md
Making a small update to the CLs WG notes because I didn't see this small point/analogy captured and wanted to make sure it didn't get lost.
> Minor update to CLs WG notes

- proposals/lock-object.md
- proposals/native-lock.md
[Rendered markdown](https://github.com/jjonescz/csharplang/blob/NativeLock-02/proposals/lock-object.md)
> Update `Lock` object speclet

- proposals/csharp-10.0/improved-definite-assignment.md
Hi @BillWagner，I've fixed the broken links. Please verify. Thanks!
Task: https://dev.azure.com/msft-skilling/Content/_workitems/edit/214777
> Fix broken links - wiwagn

- proposals/extensions.md
> Add details to lookup rules for for extensions

- meetings/working-groups/roles/extensions-wg-2024-03-05.md
FYI @MadsTorgersen @jjonescz @AlekseyTs @333fred
> Publish notes from extensions WG 2024-03-05

- proposals/params-collections.md
Related to https://github.com/dotnet/csharplang/issues/8061.
> Update params-collections.md based on recent LDM decision

- proposals/partial-properties.md
> Partial properties cannot explicitly implement interface methods

- proposals/first-class-span-types.md
Add the answers to open questions to the proposal.
> Update first-class-span proposal from LDM

- meetings/2024/README.md
- proposals/overload-resolution-priority.md
Some spec updates with answers to LDM questions and a few followups.
> Overload resolution priority spec updates

- proposals/csharp-12.0/collection-expressions.md
See details at: https://github.com/dotnet/roslyn/issues/70253
> Spec LDM decision that collection expressions targeting IEnumerable<T> implement nongeneric IList

- meetings/working-groups/roles/extension-wg-2024-06-07.md
> Add extension WG meeting notes on type erasure codegen

- proposals/extensions.md
> Add extension codegen details

- proposals/overload-resolution-priority.md
As discussed on https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-06-17.md#overload-resolution-priority-questions.
> Update overload resolution priority with LDM decisions

- proposals/semi-auto-properties.md
@CyrusNajmabadi @jnm2 @cston for your thoughts.
> Add open questions for partial properties interaction with field keyword

- meetings/working-groups/roles/extension-wg-2024-06-21.md
> Publish notes from extensions WG 2024-06-21

- proposals/first-class-span-types.md
Based on LDM decision and discussion.
> Update first-class Span open question about extension receiver break

- proposals/TypeUnions.md
for discussion tomorrow in LDM
> Add TypeUnions.md

- proposals/extensions.md
> Add type erasure details

- meetings/working-groups/field-keyword/FK-2024-06-26.md
> Polish and clarify prior field WG notes

- meetings/working-groups/field-keyword/FK-2024-08-07.md
> Fix typos in WG notes

- proposals/collection-expressions-better-conversion.md
> Prefer element type conversions over collection type conversion comparisons

- proposals/overload-resolution-priority.md
These are generating warnings when published on Learn
> Add path for links

- proposals/csharp-13.0/collection-expressions-better-conversion.md
- proposals/csharp-13.0/esc-escape-sequence.md
- proposals/csharp-13.0/lock-object.md
- proposals/csharp-13.0/method-group-natural-type-improvements.md
- proposals/csharp-13.0/overload-resolution-priority.md
- proposals/csharp-13.0/params-collections.md
- proposals/csharp-13.0/partial-properties.md
- proposals/csharp-13.0/ref-struct-interfaces.md
- proposals/csharp-13.0/ref-unsafe-in-iterators-async.md
This fixes the build errors on dotnet/docs#42623
> Add or update the speclet disclaimer

- proposals/field-keyword.md
Fixes a code sample reported by a community member, removes an extra blank line from another code sample, and documents decisions from Monday's LDM.
> Field keyword/updates

- meetings/2024/LDM-2024-02-21.md
- proposals/ref-out-lambda-params.md
- proposals/simple-lambda-parameters-with-modifiers.md
https://github.com/dotnet/csharplang/issues/338
> Update proposal for simple lambda parameters with modifiers

- proposals/csharp-11.0/low-level-struct-improvements.md
Related to https://github.com/dotnet/roslyn/issues/75592.
> Fix cyclic assignment ref safety docs

- meetings/working-groups/extensions/anonymous-extension-declarations.md
I'm incorporating several good points of feedback, either as changes or additional alternatives.
> Incorporate feedback to anonymous-extension-declarations

- proposals/first-class-span-types.md
Follow up on https://github.com/dotnet/csharplang/pull/8574.
> Note a possible ambiguity do to the new proposed betterness rule

- proposals/extensions.md
> Copy latest extensions proposal as baseline for new spec

- proposals/csharp-13.0/params-collections.md
- proposals/csharp-13.0/ref-struct-interfaces.md
- proposals/csharp-13.0/ref-unsafe-in-iterators-async.md
I'd merged before I saw the updated comments. This PR addresses the comments by @jjonescz
> fast follow to #8769

- proposals/csharp-9.0/skip-localsinit.md
> Fix a typo

- proposals/extensions.md
Relates to test plan https://github.com/dotnet/roslyn/issues/76130
> Add section on metadata for extensions

- proposals/csharp-8.0/using.md
Fixes https://github.com/dotnet/csharplang/issues/9023
> Fix using syntax

- meetings/working-groups/field-keyword/field-assignment-in-constructor.md
- meetings/working-groups/field-keyword/fieldof.md
> Add proposal for `fieldof()`

- proposals/left-right-join-in-query-expressions.md
This is a draft of the left/right join proposal tracked by #8947 and discussed in #8892.
> Proposal for query expression left/right join clause

- proposals/first-class-span-types.md
Removing answered questions + adding links to LDMs for better traceability.
> Clean up first-class span speclet

- proposals/extensions.md
Relates to test plan https://github.com/dotnet/roslyn/issues/76130
> Extensions: Clarify accessibility in metadata format

- meetings/2025/README.md
- proposals/readonly-setter-calls-on-non-variables.md
@jaredpar indicated that this is a change that would need to be discussed. Context: https://github.com/dotnet/csharpstandard/issues/1277#issuecomment-2680341325
> [Proposal] Readonly setter calls on non-variables

- proposals/extensions.md
Relates to test plan https://github.com/dotnet/roslyn/issues/76130
> Extensions: use speakable implementation names

- proposals/ignored-directives.md
https://github.com/jjonescz/csharplang/blob/sprint-spec-01/proposals/ignored-directives.md
> Add proposal for ignored directives

- proposals/extensions.md
@AlekseyTs @jjonescz for review. Thanks
> Extensions: adjust rules for `[Extension]` attribute

- meetings/working-groups/extensions/Extension-API-docs.md
We discussed this in the LDM meeting on 2025-02-24. This edit captures feedback from LDM.
I'll wait to merge until I see the notes from Monday, in case I missed anything.
> Update based on LDM meeting

- proposals/extensions.md
FYI @AlekseyTs @jjonescz @MadsTorgersen
> Extensions: update with decisions from LDM 2025-03-17

- proposals/collection-expression-arguments.md
- proposals/dictionary-expressions.md
Updates to dictionary expressions and collection expression arguments based on decisions from [LDM-2025-03-12](https://github.com/dotnet/csharplang/blob/main/meetings/2025/LDM-2025-03-12) and [LDM-2025-03-17](https://github.com/dotnet/csharplang/blob/main/meetings/2025/LDM-2025-03-17).
> Dictionary expressions: resolve answered questions

- proposals/extensions.md
FYI @KathleenDollard (thanks for catching that)
> Extensions: fix typo

- proposals/collection-expression-arguments.md
- proposals/dictionary-expressions.md
Add resolutions from [LDM-2025-03-05](https://github.com/dotnet/csharplang/blob/main/meetings/2025/LDM-2025-04-14.md).
> Dictionary expressions: resolve open questions

- proposals/extensions.md
The locale is generating a build issue on the docs site.
> remove locale

- proposals/ignored-directives.md
Related to https://github.com/dotnet/roslyn/issues/78301.
Implemented in https://github.com/dotnet/roslyn/pull/78411.
> Update #! restrictions in ignored directives proposal

- proposals/collection-expression-arguments.md
Minor updates to open questions and method signatures for interface target types.
> Collection arguments: updates

- proposals/user-defined-compound-assignment.md
Adding the docs for this feature, so adding the feature speclet disclaimer.
> Add the note about feature speclets for Learn

- proposals/ignored-directives.md
Add the disclaimer as this is now getting published on Learn.
> Add speclet disclaimer

- meetings/working-groups/discriminated-unions/Closed Enums.md
- meetings/working-groups/discriminated-unions/Closed Hierarchies.md
- meetings/working-groups/discriminated-unions/Nominal Type Unions.md
Adds short proposals for Closed Enums, Closed Hierarchies and Nominal Type Unions to facilitate LDM discussion.
> Add more mini-proposals for unions

- proposals/csharp-14.0/extension-operators.md
- proposals/csharp-14.0/extensions.md
- proposals/csharp-14.0/field-keyword.md
- proposals/csharp-14.0/first-class-span-types.md
A couple path typos, and removing locales.
Fast follow to #9606
> Fix some final build warnings on learn

- proposals/inference-for-constructor-calls.md
- proposals/inference-for-type-patterns.md
- proposals/target-typed-generic-type-inference.md
Add more motivation, explanation and detail to the three proposals.
> Improve type inference proposals

- proposals/target-typed-generic-type-inference.md
Adds a section that shows how the proposed type inference capability is already supported by today's language and compiler with a simple systematic rearrangement of the code.
> Add implementation considerations on target-typed inference

- proposals/using-with-a-discard.md
Champion issue: https://github.com/dotnet/csharplang/issues/8606
/cc @333fred as champion
> Create proposal for using discard statements

- proposals/collection-expressions-in-foreach.md
Added a disclaimer and corrected the champion issue reference.
> Update collection expressions proposal with disclaimer
