dotnet/csharplang

spec/documentation-comments.md

Prior to this change, the grammar showed that the asterisk in the '*/' pair
that closes a block comment was optional. This change updates the grammar
rule to require at least one asterisk to appear.

Require an asterisk to close a delimited_doc_comment

---

proposals/proposal-template.md

Some people aren't native English speakers and they might have problems understanding the text when abbreviations are used.

Remove abbreviations from the text

---

spec/expressions.md

The issue was the pipe character in `x | y`, which isn't allowed in a table since the table uses that character to represent column/cell breaks. To keep the code formatting, the expression needed to be written as 
```
<code>x &#124; y</code>
````

Fixes #160.

---

proposals/static-delegates.md

FYI. @MadsTorgersen, @gafter 
This is the official proposal for https://github.com/dotnet/csharplang/issues/80, which @jaredpar has agreed to champion.

Adding the static-delegate proposal.

---

proposals/readonly_locals.md

https://github.com/dotnet/csharplang/issues/188
https://github.com/dotnet/roslyn/issues/115

Add proposal for readonly locals/parameters

---

proposals/default-interface-methods.md

Fix typo in default interface methods proposal

---

spec/namespaces.md

There was a backtick where it should have been an asterisk.

Typo in markup

---

Language-Version-History.md

current Url for "Reference assemblies" point to a not fond URL, I've just added to correct Url

Correct URL for "Reference assemblies"

---

proposals/patterns.md

Corrected patterns.md to use discard pattern ('_') in examples instead of star (`*`).

Corrected patterns.md to use discard pattern ('_') in examples

---

proposals/csharp-7.0/throw-expression.md

Clarify the specified semantics of a throw expression.

---

proposals/non-trailing-named-arguments.md

Clarify spec change.
Add notes about subtleties of overload resolution and misleading diagnostics.

Update non-trailing named arguments proposal

---

proposals/span-safety.md

Also normalize file format for a couple of C# LDM notes.

Add draft language rules for ref-like types.

---

proposals/span-safety.md

Although C# has the `readonly` keyword, the common usage is to have the term hyphenated as _read-only_.
This would mean the term should have a capital O. I.e. `ReadOnlySpan<T>` rather than `ReadonlySpan<T>`.
This matches `IReadOnlyCollection` and friends.

Capitalisation of ReadOnlySpan<T>

---

spec/classes.md

I noticed a typo in the property_initializer syntax for classes

Fix typo in property_initializer syntax

---

meetings/2014/README.md

Note that I have only changed lines 99 and 100.
I believe the other lines that appear changed were modified by GitHub, which said:
>  We've detected the file encoding as windows-1252. When you commit changes we will transcode it to UTF-8.

Fixed formatting in 2014 meetings README

---

proposals/caller-argument-expression.md

I'd completely overlooked extension methods when I first thought of the CAE proposal, but luckily it didn't ruin everything. I've updated the spec to explain how the attribute will behave when it references a `this` parameter in response to https://github.com/dotnet/csharplang/issues/287#issuecomment-312611587.
/cc @yaakov-h, @gafter

Update CAE spec for extension methods

---

spec/README.md
spec/classes.md

* Added `async` modifier to grammar
* Fixed link to *Async functions*
* Added *Async functions* to TOC

Small fixes related to async

---

Language-Version-History.md

Links were broken by https://github.com/dotnet/csharplang/pull/870.
Fixes https://github.com/dotnet/csharplang/issues/937.

Fix links in Language Version History

---

proposals/csharp-7.2/ref-local-reassignment.md

Here is a proposed spec for ref local reassignment
/cc @dotnet/ldm @dotnet/roslyn-compiler @agocke

Spec for ref local reassignment.

---

proposals/blittable.md

This is the initial proposal for the blittable feature as tracked by #187.

Initial blittable proposal

---

proposals/csharp-7.2/readonly-ref.md

Updating readonly reference proposal to match the final form of features.
Incorporates decisions, changes and motivation from various sources, documents and discussions.
The goal is to have all the relevant information in one place and describe the expected behavior of the actual implementation.
Fixes:https://github.com/dotnet/roslyn/issues/23450
Fixes:https://github.com/dotnet/roslyn/issues/22950

Updating readonly reference proposal to match the final form of features.

---

spec/expressions.md

Just fixed typo in unary operators section.
Operator '*' is in the position of '-'.

Fix operator '*' to '-' in unary operators section

---

proposals/stackalloc-array-initializers.md

In short: Ordinary arrays can be created through the following syntax:
```C#
new int[3]
new int[3] { 1, 2, 3 }
new int[] { 1, 2, 3 }
new[] { 1, 2, 3 }
```
We should allow stack allocated arrays be created through:
```C#
stackalloc int[3]				// currently allowed
stackalloc int[3] { 1, 2, 3 }
stackalloc int[] { 1, 2, 3 }
stackalloc[] { 1, 2, 3 }
```

Stackalloc array initializers.

---

proposals/skip-localsinit.md

It does not seem to be big enough to be a real C# language feature (as in "required by all conforming C# implementations"), but we can have it as a compiler feature where compiler may optionally recognize a specific attribute as a directive/hint to omit the flag.
There are few scenarios where forced zero-initialization may noticeably impact performance. 
The feature could be implemented as a compiler switch - similar to `/optimize`, but it could be more valuable when can be applied more selectively to specific methods or types.

Allow suppressing emit of `localsinit` flag via an attribute.

---

proposals/blittable.md

This updates the blittable design to reflect the most recent design
meeting on the subject. Summary of the changes:
1. Decided on `unmanaged` over `blittable`: This is the term used by
the spec and prior art (in F#). Additionally `blittable` is actually
a stronger constraint than what we actually need here.
2. Removed the struct declaration section: After further examination
it was decided that forcing existing structs to be annotated with
`unmanaged` before meeting the `unmanaged` constraint would severely
limit the feature. Decided to focus on the constraint here only.
Note: even though we changed the name I still kept the doc as
blittable.md for now to avoid breaking links and keeping doc history.

Blittable design update

---

meetings/2014/LDM-2014-01-06.md
meetings/2014/LDM-2014-02-03.md
meetings/2014/LDM-2014-07-09.md
meetings/2014/LDM-2014-10-01.md
meetings/2015/LDM-2015-01-21.md
meetings/2015/LDM-2015-01-28.md
meetings/2015/LDM-2015-03-18.md
meetings/2015/LDM-2015-04-14.md
meetings/2015/LDM-2015-08-18.md
meetings/2015/LDM-2015-09-01.md
meetings/2015/LDM-2015-09-02.md
meetings/2015/LDM-2015-09-08.md
meetings/2015/LDM-2015-10-07-Design-Review.md
meetings/2015/README.md
meetings/2016/LDM-2016-02-29.md
meetings/2016/LDM-2016-07-13.md
meetings/2016/LDM-2016-11-01.md
meetings/2017/LDM-2017-01-11.md
meetings/2017/LDM-2017-01-18.md
meetings/2017/LDM-2017-03-01.md
meetings/2017/LDM-2017-03-15.md
meetings/2017/LDM-2017-03-21.md
meetings/2017/LDM-2017-08-07.md
meetings/2017/LDM-2017-08-16.md
meetings/2017/LDM-2017-08-28.md
meetings/2017/LDM-2017-10-09.md
meetings/2017/LDM-2017-10-18.md
meetings/2017/LDM-2017-10-25.md
meetings/2017/LDM-2017-11-29.md

Submitting this as a separate PR since I wasn't sure whether you're interested at all in fixing "archived" documents.

Fix typos in `meetings`

---

proposals/async-streams.md

need to cast to the type in case it is implemented explicitly and the viable alternative should also implement

should implement IAsyncDisposable correctly

---

meetings/2017/LDM-2017-10-11.md

Especially for non-native English readers, the phrase
> even though it creates a hole array of undesired nulls
sounds a bit weird.

Minor, but important typo

---

proposals/tuple-equality.md

Tagging @MadsTorgersen @dotnet/roslyn-compiler for review.
Update: I will update this proposal with input from Neal and Mads:
- the existence of a conversion from `e` to a 2-tuple does not affect `e == (x, y)` (ie. it fails)
- there is an open question on `(x, y) == (1, "")` versus `(x, y) == (1, null)` when there is an `==` between `x` and `byte`. The second one should clearly succeed since the tuple `(1, null)` has no natural type, we can give it type `(byte, string)`. But should the first one succeed too? (it does in my current prototype, but we'll have to figure out how to word this because the conversion from `1` to `byte` only works on constants, but the tuple is not a constant). I should test `(byte, string) t = ...` and `(byte x, string y) = ...` in those cases too.
Relates to …

Proposal for tuple equality/inequality comparisons

---

intrinsics.md

This is an alternate proposal for the compiler intrinsicts feature:
https://github.com/dotnet/csharplang/issues/191
https://github.com/dotnet/roslyn/issues/11475
This alternate design proposal comes after reviewing a prototype implementation
of the original proposal by @msjabby as well as the use throughout a significant
code base.
This design was done with significant input from @mjsabby, @tmat and @jkotas.

Compiler intrinsics

---

proposals/csharp-7.3/auto-prop-field-attrs.md

We use [Allman style](http://en.wikipedia.org/wiki/Indent_style#Allman_style) braces, where each brace begins on a new line. 
We should use `_camelCase` for internal and private fields
See: [coding-style.md](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md )

Fix code format

---

proposals/ranges.md

Update range proposal

---

proposals/csharp-7.2/readonly-ref.md

An `in` parameter must have the attribute `[IsReadOnly]`. It may have the attribute `[In]` if and only if it is either abstract or virtual.
issue #1655

abstract/virtual parameters use InAttribute

---

spec/expressions.md
spec/introduction.md

Fixes dotnet/docs#6335
Because these are in a code fence, the back-slash was rendering on the docs platform. This still renders correctly in GFM, and on docs.
/cc @HankiDesign

don't escape vertical bar in code fence

---

proposals/nullable-enhanced-common-type.md

See https://github.com/dotnet/csharplang/issues/881
As requested by LDM about a year ago

Add support for common type of `int` and `double?`.

---

meetings/2018/README.md

I've added a section to the end of the 2018 README to track the agenda for upcoming meetings.

Add upcoming meetings

---

spec/expressions.md
spec/introduction.md

Fixes https://github.com/dotnet/docs/issues/8034.
I didn't format the table. If you want to, please directly modify them.

 Fix vertical escape in table 

---

proposals/function-pointers.md

This is the function pointer feature reviewed in LDM on 10/15. Notes for that meeting are [here](https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-10-15.md). This is an alternate approach to [intrinsics](https://github.com/dotnet/csharplang/blob/master/proposals/intrinsics.md) for exposing the `calli` and `ldftn` instructions.
This is the proposal as discussed in the meeting. Uploading this version so that the notes will make a bit more sense. Will upload a new version, based on the changes discussed in LDM, in the next few days.

Function Pointer Proposal

---

spec/conversions.md

fixed a simple typo, that is "**contravariant**" is a single word.

Fix typo in conversions.md

---

proposals/null-conditional-await.md
proposals/readonly_locals.md

- Added code highlighting to a single-char variable reference
- Replaced funky quotes with straight ones

Fix a few formatting nits

---

spec/classes.md

Since `right_shift` is another production rule and not a literal sequence of characters, is should not be enclosed in quotes.

Unquote right_shift in the syntax for overloadable_binary_operator

---

spec/documentation-comments.md

A ' quote was listed where a \` should exist (as far as I know).
Also formatted neighbouring character sequences as code blocks for consistency.

Fix generic escape character and formatting

---

proposals/using.md

Proposal to add `using` local variable declarations and the `using` pattern to the language.

Using patterns and declarations

---

proposals/patterns.md

There were some not updated usages of *match_expression*. I've replaced all of them with *switch_expression* as I guess was intended.

Upate patterns.md - always use switch_expression

---

proposals/patterns.md

- Allow trailing comma in property pattern
- Allow trailing comma in switch expression
- Rename deconstruct_subpattern to positional_subpattern

Minor changes to patterns spec:

---

meetings/2019/README.md
proposals/default-interface-methods.md

Moving closed issues to the specification.
/cc @MadsTorgersen @AlekseyTs @jaredpar

Update default interface method spec per LDM decisions

---

proposals/default-interface-methods.md

Require that `Base` contains a *most specific override* for `M` in the expression `base(Base).M()`.

Require `base(T).M()` has *most specific override*

---

spec/lexical-structure.md

The current syntax does not require a multiline comment to end with '*/'.
So,
```antlr
delimited_comment
: '/*' delimited_comment_section* asterisk* '/'
;
```
should be:
```antlr
delimited_comment
: '/*' delimited_comment_section* asterisk+ '/'
;
```

fix grammar rule

---

spec/lexical-structure.md

'close_brace_escape_sequence' is not highlighted

fix indent

---

spec/namespaces.md

No method `A` in the Class `C`.
Instead, there is a static field `A`.

Fix example description

---

spec/lexical-structure.md

According to the current definition of the delimited comment in the [specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure#comments) the line 
```csharp
/*/
```
is a valid comment, which is not true.

spec/lexical-structure.md: fixed definition of delimited comment

---

meetings/2018/LDM-2018-10-17.md

Add the details of a question (Properties with a private accessor) so the resolution makes sense in context.
/cc @agocke @AlekseyTs

Properties with a private accessor (add question to notes where it is answered)

---

proposals/csharp-8.0/ranges.md

This change reflects the recent CoreFX and language decisions about
naming and signature of the Index/Range types & members.

Add well-known member details

---

proposals/readonly-instance-members.md

Added detail to the speclet about how to handle `readonly` events. This design is meant to be as consistent as possible with what's allowed within a `readonly struct` declaration.

Specify readonly members behavior for events

---

proposals/csharp-7.0/pattern-matching.md

When this file was moved into the 7.0 proposals directory, the link to records should have been updated to the parent directory.
found while working on dotnet/docs/#11026
/cc @jcouv @MadsTorgersen

The spec for records is still in the parent directory

---

proposals/format.md

This proposal is being discussed at LDM on 3/4/2019.

Efficient params and string formatting

---

proposals/csharp-8.0/patterns.md
proposals/records.md

The 8.0 pattern matching spec links to records.md, and vice-versa.
It looked like Deconstruct semantics are described in 8.0, in the "Positional pattern" section. I added an anchor tag to resolve to that section.
This would fix the build warnings in dotnet/docs#11026
/cc @jcouv @MadsTorgersen

fix two more broken links 

---

proposals/csharp-7.1/async-main.md
proposals/csharp-7.1/generics-pattern-match.md
proposals/csharp-7.1/infer-tuple-names.md

These had two sets of changes:
1. use `csharp` as the language identifier for code fences.
1. use relative links to other articles in the dotnet/csharplang repo that are being published on docs.microsoft.com so those links resolve to the article published there from that site.
/cc @mairaw @jcouv @agocke

markdown lint for C# 7.1 proposals

---

proposals/csharp-7.0/binary-literals.md
proposals/csharp-7.0/digit-separators.md
proposals/csharp-7.0/local-functions.md
proposals/csharp-7.0/out-var.md
proposals/csharp-7.0/pattern-matching.md
proposals/csharp-7.0/throw-expression.md

These changes are to improve the experience for publishing these proposals.
One change should be carefully reviewed to ensure I didn't introduce any technical errors:
I translated the binary literals grammar into ANTLR to match all other specs and proposals.  See changes in proposals/csharp-7.0/binary-literals.md
Other changes are:
1. Use  consistent ATX headers, with one H1 per proposal.
1. use `csharp` as language identifier in code snippets
1. Use relative links to other markdown from the dotnet/csharplang repo. That way, when published on docs.microsoft.com, the links will resolve to the publsihed articles on the same site. (Links to content not being published are not modified.)
1. spelling / capitalization found by the lint tool.
/cc @mairaw @jcouv @agocke

markdown lint changes to C# 7.0 proposals

---

proposals/csharp-7.2/conditional-ref.md
proposals/csharp-7.2/leading-separator.md
proposals/csharp-7.2/non-trailing-named-arguments.md
proposals/csharp-7.2/readonly-ref.md
proposals/csharp-7.2/span-safety.md

Primarily these changes:
1. ATX style headers.
1. `csharp` as the language identifier
1. relative link to other published proposals.

update 7.2 proposals for markdown lint concerns

---

proposals/csharp-7.3/auto-prop-field-attrs.md
proposals/csharp-7.3/blittable.md
proposals/csharp-7.3/expression-variables-in-initializers.md
proposals/csharp-7.3/indexing-movable-fixed-fields.md
proposals/csharp-7.3/pattern-based-fixed.md
proposals/csharp-7.3/ref-local-reassignment.md
proposals/csharp-7.3/stackalloc-array-initializers.md
proposals/csharp-7.3/tuple-equality.md

These were:
1. adding `csharp` as the language identifier.
1. making relative links to content published on docs.microsoft.com
1. small grammar fixes.

markdown fixes for 7.3 proposals

---

proposals/default-interface-methods.md

In the modified sample, I think these base interfaces were missing.
I was reviewing this and taking notes as I start work on dotnet/docs#11604. This sample looked incorrect based on the proposed syntax.
I wasn't sure if `IC` was meant to derive only from `IB` or from `IB` and `IA` in its declaration.

Add base interfaces to declarations

---

proposals/csharp-7.2/readonly-ref.md

The sample returns a field that is not defined in the sample. I assume the code should return the referenced element in the array.
Fixes dotnet/docs#12301

Return storage that exists

---

meetings/2014/LDM-2014-10-01.md

Spaces inside emphasis markers

fix: MD037/no-space-in-emphasis

---

proposals/csharp-8.0/null-coalescing-assignment.md

This is using the language that we agreed upon in email prior.

Update ??= proposal with changes from LDM

---

spec/README.md

The ECMA standard for C# 5.0 has already been released, so this is no longer accurate. It would be nice if the current status of standardizing C# 6.0 could be included here, but I don't have that information, so I just removed the outdated information.

Remove outdated info from spec index

---

spec/documentation-comments.md

Fixes https://github.com/dotnet/csharplang/issues/2435 and updates `<remark>`  to `<remarks>`, per the original text in [ECMA-334](https://ecma-international.org/publications/files/ECMA-ST/ECMA-334.pdf) §D.3.12.

Recommend <remarks> rather than <remark>

---

spec/basic-concepts.md
spec/classes.md
spec/delegates.md
spec/documentation-comments.md
spec/enums.md
spec/expressions.md
spec/introduction.md
spec/lexical-structure.md
spec/statements.md
spec/structs.md
spec/unsafe-code.md

US 1583733 - Fix CATS P1 issues by adding missing language IDs to code blocks.
- Used "console" for C# command-line compiler examples.
- Used "console" for sample program output displayed on the console.

US 1583733 Add missing language IDs - 62

---

Language-Version-History.md

This page is include C# and Visual Studio version that shipped with, this unnecessary description destroy Uniformity of C# 8 with other C# version in this page.

Tweak C# version history

---

spec/unsafe-code.md

Fixes dotnet/docs#11067
`int` -> `IntPtr` for `HANDLE`
`int` -> `UIntPtr` for `SIZE_T`
BTW the coding styles in this repo are terrible.
/cc @Thraka @BillWagner

 Fix unsafe examples

---

proposals/csharp-7.2/private-protected.md
proposals/csharp-7.2/readonly-ref.md

These two links both contained the "en-us" locale. That directs  readers to the English version, rather than the localized version based on their browser environment.

remove locale

---

spec/types.md

The exponent range is -1075 - 970, not 1075 - 970.
Fixes dotnet/docs#15679

fix sign error

---

spec/conversions.md

There is the [section](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#implicit-interpolated-string-conversions) about implicit interpolated string conversions, but they are not in the list of implicit conversions.

Mention implicit interpolated string conversions in the list of implicit converions

---

proposals/csharp-7.0/tuples.md

Fixes dotnet/docs#15046
This PR updates the C# 7.0 proposal document so that it could be used as a proposed delta to the C# standard.
To make these edits, I did the following:
1. Update the language to conform to the standard language.
1. Update the changes based on C# LDM meeting notes in this repo, and the dotnet/roslyn repo. Note that I only incorporated changes that were released in C# 7.0. Later changes to tuples (such as equality) are not included.
1. Edit and review.
1. Test against current compiler set to `<LangVersion>7.0</LangVersion>`.
This is the first PR for this larger task. I have notes for reviewers, and questions about how to continue proceeding. 
Questions / notes for reviewers:
1. Are the proposals useful in their current form? This PR updates the tuples proposal in …

First set of changes for tuples from feature spec and LDM notes.

---

proposals/csharp-7.0/binary-literals.md

Remove trailing colon from some productions in the grammar

Binary literals: Minor editorial fixes

---

proposals/csharp-7.0/digit-separators.md

Remove trailing colons from production names in the grammar

Digit-separators: Minor editorial fixes

---

proposals/function-pointers.md

- Preventing -> Presenting (confused me for a second while reading the doc)
- Fix markdown link

Fix typos in function pointers proposal

---

proposals/csharp-6.0/enum-base-type.md
proposals/csharp-7.0/expression-bodied-everything.md
proposals/csharp-7.0/tuples.md
proposals/csharp-7.2/readonly-struct.md
proposals/csharp-7.2/ref-extension-methods.md
proposals/csharp-7.2/ref-struct-and-span.md
proposals/csharp-7.3/enum-delegate-constraints.md
proposals/csharp-7.3/ref-loops.md
proposals/csharp-8.0/alternative-interpolated-verbatim.md
proposals/csharp-8.0/async-using.md
proposals/csharp-8.0/constraints-in-overrides.md
proposals/csharp-8.0/constructed-unmanaged.md
proposals/csharp-8.0/notnull-constraint.md
proposals/csharp-8.0/obsolete-accessor.md
proposals/csharp-8.0/shadowing-in-nested-functions.md
proposals/csharp-8.0/unconstrained-null-coalescing.md

This PR adds placeholders for specifications that are currently missing from the csharplang repository. The intent is to add breadcrumbs to (1) encourage feature owners to fill in (or move) more complete language specifications to this repository, and (2) give a hint to other authors (such as ECMA or our docs team) what features are actually in each release.  Some of the features indexed here have no documentation whatsoever anywhere else.
@MadsTorgersen @jaredpar

Add placeholder documents for missing specifications.

---

proposals/function-pointers.md

The summary for these specs are:
- Value parameters are treated as contravariant.
- Value return types are treated as covariant.
- Reference parameter/return types and modifiers must match exactly.
- Calling convention must match exactly.
- An address-of expression that contains method group with exactly 1 static method is convertible to `void*`.

Add conversions spec for function pointers

---

proposals/local-function-attributes.md

Related to dotnet/roslyn#38801
This adds the draft spec from #3008 into the repository.
@gafter please let me know if this should go somewhere else, or if any other action is needed.

Add draft spec for local function attributes

---

proposals/function-pointers.md

This fixes a very similar problem to https://github.com/dotnet/csharplang/issues/3277, where this code is unable to be resolved:
```cs
interface I1{}
interface I2{}
public unsafe class C : I1, I2 {
void M(I1 i) {}
static void M(I2 i) {}
public void M1() {
delegate*<C, void> a = M; // Ambiguous because both M's are applicable
}
}
```
With this change, the instance method M is not applicable, so there is no ambiguity.

Only allow static methods for applicable members

---

proposals/function-pointers.md

This forbids all binary operators except comparison operators.

Update function pointers proposal for binary operators.

---

proposals/function-pointers.md

Added the spec proposal discussed over email for representing `in` and `out` parameters.

Add metadata representation section for in and out

---

proposals/init.md

Permit init-only initialization in attribute usages

---

proposals/csharp-8.0/null-coalescing-assignment.md

The feature is available in C# 8. I can't see guidance on what should be updated in these docs to reflect that, so not sure if what I've changed is what should be changed!

Updated status of null coalescing assignment from proposed to implementation completed

---

proposals/records.md

Try to bring the proposal in line with LDM decisions. Inheritance is somewhat described, but there
have been no affirmative decisions by LDM so this is still in flux

Bring records proposal up to date 

---

proposals/extension-getenumerator.md

Added the spec for extension GetEnumerator. The only change from https://github.com/dotnet/csharplang/issues/3194 was the additional line about the refkind in overload resolution.

Add spec for extension GetEnumerator

---

proposals/records.md

Update records spec to clarify that both `get` and `init` accessors of `abstract` properties are overridden.

Records: Override abstract property get and init accessors

---

proposals/function-pointers.md

This adds the changes to extensible calling conventions and support for UnmanagedCallersOnlyAttribute.

Update the calling convention and UnmanagedCallersOnly attribute.

---

meetings/2020/README.md

The link to the Design Notes for June 24th was set to June 22nd.

Fixed typo in Readme.md

---

proposals/csharp-9.0/covariant-returns.md
proposals/csharp-9.0/extending-partial-methods.md
proposals/csharp-9.0/lambda-discard-parameters.md
proposals/csharp-9.0/local-function-attributes.md
proposals/csharp-9.0/native-integers.md
proposals/csharp-9.0/target-typed-conditional-expression.md

These were found building dotnet/docs#19736
- Add correct folders for several spec references.
- Correct casing of one anchor tag.
- Replace absolute links with relative links.

fix a number of broken links

---

proposals/csharp-9.0/top-level-statements.md

The previous table style worked for GFM, but was not valid for markdig.

Fix table rendering

---

proposals/csharp-9.0/records.md

@dotnet/roslyn-compiler for review. This is a proposal for shape of ToString synthesized members.

Add ToString and PrintMembers to records

---

proposals/csharp-9.0/covariant-returns.md

Note that covariant returns does not apply for ref-returning methods.

Update spec for covariant returns.

---

proposals/csharp-9.0/covariant-returns.md

This fixes a build warning in dotnet/docs.

Add H1 to convariant returns

---

proposals/csharp-9.0/native-integers.md

Recent updates for native integers:
- Reference `NativeIntegerAttribute` encoding document in dotnet/runtime
- Report errors binding to operators when compiling with earlier language version

Recent updates for native integers

---

proposals/csharp-9.0/function-pointers.md

Restoring a code example removed by eade6b9, per @333fred. See https://github.com/dotnet/csharplang/pull/3848#issuecomment-687390497.

Restore missing code example from Function Pointers doc

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/proposal_template.md

Adds an issue template for full proposals, and adds a link to creating a new discussion with a description for when each should be chosen.

Add issue templates

---

proposals/csharp-9.0/records.md

See https://github.com/dotnet/roslyn/pull/47515#issuecomment-691319952

Update records spec with new warning

---

proposals/csharp-9.0/patterns3.md

Fixes https://github.com/dotnet/roslyn/issues/44102

Update pattern spec for narrowed type of ITuple pattern

---

proposals/low-level-struct-improvements.md

This design covers adding the following features to C# for low level
struct performance improvements:
- Allowing `ref struct` to contain `ref` fields.
- Allowing `struct` and `ref struct` to return `ref` to their fields.
- Allowing safe fixed buffers for unmanaged and managed types.
Note: the section on providing parameter escape notations is incomplete
at this time. I will send a PR in the future once I finalize this
portion. Feel free to still leave comments though.

Proposal: Low level struct improvements

---

proposals/csharp-9.0/records.md

The Roslyn compiler in VS 2019 requires a comma between the argument_list and the interface list to compile.
**With comma:**
**Without comma:**

Add missing `,` to record_base rule

---

proposals/csharp-9.0/records.md

Since we allow `class C { };`...
Tagging @dotnet/roslyn-compiler for review

Allow semi-colon after block body for record declarations

---

proposals/csharp-9.0/records.md

Note: I'm not calling out restricted types, which are an existing restriction on fields.
Although we don't typically document warnings in the spec, I think it's okay to include the unread parameter warning.
There are two open questions for LDM:
- confirm whether pointer types or unsafe types are disallowed for instance fields in records
- confirm the warning on unread positional parameters

Disallow pointer types for record parameters

---

proposals/csharp-9.0/init.md

Fixes https://github.com/dotnet/csharplang/issues/3884.

Add `init` accessors in `readonly struct`s and `readonly` properties

---

proposals/csharp-9.0/nullable-reference-types-specification.md

This makes the following updates to the NRT spec
- Examples for scenarios that commonly trip up customers
- Clarification on when expressions have the null state "maybe default"
vs. "maybe null"
- Minor langauge cleanup

NRT spec updates

---

proposals/low-level-struct-improvements.md

This updates the low level struct proposal section on annotations for
parameters that do not escape. This is intended to remove low level
friction points that result from using `ref struct` as arguments to
instance methods on `ref struct`.

Parameter does not escape annotation

---

meetings/2020/LDM-2020-06-24.md
meetings/2020/LDM-2020-10-26.md
meetings/2020/LDM-2020-12-14.md
proposals/variance-safety-for-static-interface-members.md

'Retcon' is an abbreviation for "retroactive continuity." The word 'continuity' doesn't start 'conn.'
A second 'n' would be added as usual for 'retconned' and 'retconning.'

Fix typo 'retconn'

---

proposals/csharp-9.0/records.md
proposals/record-structs.md

We'll queue this up for discussion in LDM in the coming weeks.
My biggest concern is with allowing field initializers when a primary constructor (ie. with parameters) is present, since default values for the fields are still possible.
This and other smaller open questions are listed at the bottom of the document.
FYI @dotnet/roslyn-compiler @MadsTorgersen @BillWagner @dotnet/csharplangdesign

Spec for record structs

---

proposals/csharp-9.0/function-pointers.md

I've taken a stab at creating a spec for function pointer type inference, basing it off the rules for constructed and delegate type inference. I'm unsure that I actually got the wording right that reflects the actual rules I'm implementing in https://github.com/dotnet/roslyn/pull/50249, so careful review is appreciated.

Function pointer type inference

---

proposals/rejected/static-delegates.md

The static delegates proposal was superceded by function pointers.

Remove static delegates proposal

---

proposals/csharp-9.0/records.md

Fix PrintMembers return type

---

proposals/improved-definite-assignment.md

Adding the proposal and specification together. This is identical with what is in #4240 and #4465. The specification content will soon be removed from those issues and will exist only in here. Then, spec revisions which occur in subsequent PRs can be reviewed more easily.

Add improved-definite-assignment.md

---

spec/introduction.md

"The type parameters can the be used" -> "The type parameters can then be used"

Add the missing letter

---

proposals/csharp-10.0/lambda-improvements.md

Support lambdas with attributes, explicit return type, and natural type.

Add proposal for lambda improvements

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/CODEOWNERS

I'd accidentally placed the file in a sub-folder.

Move CODEOWNERS file to correct folder

---

proposals/list-patterns.md

Tracking issue: https://github.com/dotnet/csharplang/issues/3435
Discussion: https://github.com/dotnet/csharplang/issues/1510, https://github.com/dotnet/csharplang/issues/1039, https://github.com/dotnet/csharplang/issues/898
Prototype: https://github.com/dotnet/roslyn/compare/main...alrz:list-patterns
Proposal: [Rendered](https://github.com/alrz/csharplang/blob/list-patterns/proposals/list-patterns.md)

Add list patterns proposal

---

proposals/csharp-9.0/records.md

In accordance with https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-parameters#naming-operator-overload-parameters
Related to https://github.com/dotnet/roslyn/issues/49300

Rename record equality parameters to 'left' and 'right'

---

proposals/improved-definite-assignment.md

It feels like we can't propagate "state when not null" out of conditional accesses when they are subject to certain user-defined conversions, but it is desirable to propagate out such state from built-in implicit and explicit conversions whenever possible.

Address conversions of conditional accesses in IDA

---

proposals/list-patterns.md

Tagging @dotnet/roslyn-compiler @alrz @MadsTorgersen for review.
Relates to proposal https://github.com/dotnet/csharplang/issues/3435

Spec list-pattern on enumerable collections

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/proposal_template.md

From a discussion with @333fred, @CyrusNajmabadi, @MadsTorgersen, @YairHalberstadt, incorporating suggestions by Yair and Fred
The motivation is to close any gap between how the language design team already effectively works, and expectations of community members who want to create a new issue:
- Avoiding a contributor feeling that moving to a discussion is a rejection of the time and level of quality put into their proposal. (The comprehensiveness is what the current directions emphasize.)
- Directing contributors to the right spot in the first place.
- Showing contributors that community discussions are the normal path to get a proposal that would be considered by the LDM, as opposed to thinking chances are increased by doing a big walk-up proposal, or thinking chances are lessened by …

Help to set expectations for issues up front

---

proposals/improved-interpolated-strings.md

* Split the TryFormat methods into TryFormatBaseString and TryFormatInterpolationHole. Naming is definitely subject to review, but hopefully the concept is clear.
* Added new open questions for logging scenarios after review with the ILogger folks.
* Added leeway for async rules in using the interpolated string builder for string types.
* Added open question for disposal of builder types.

Update interpolated string proposal with feedback

---

proposals/statics-in-interfaces.md

Proposed expansion of static abstract members in interfaces to support equality operators and user-defined conversions, as well ad default implementations

Add equality and conversion operators to static abstract members in interfaces

---

proposals/csharp-8.0/readonly-instance-members.md

The original code doesn't compile. `readonly` can be set on a getter or setter when only one of them is readonly. If all setters are readonly, `readonly` must be set on the property.
As this file is available in the documentation, I think this is better to keep it up to date.
- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/readonly#c-language-specification
- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/readonly-instance-members

Fix readonly property samples

---

proposals/improved-definite-assignment.md

/cc @333fred related to the change to propagate conditional state through `expr is not true` etc patterns.
Related to dotnet/roslyn#52616

Improved definite assignment: accept more bool patterns

---

proposals/csharp-8.0/ranges.md

Extremely small fix to get the example code under "Implicit Range support" to run

Update ranges.md: length -> Length

---

proposals/csharp-8.0/readonly-instance-members.md

Fix example: static struct members cannot be readonly

---

proposals/parameterless-struct-constructors.md

If a `struct` constructor calls `: this()` and the parameterless constructor is the default zero-init constructor, any fields initializers are executed in the calling constructor rather than the parameterless constructor.
Compare `S1(int)` and `S2(int)` below. Both call `: this()`. In `S1`, the parameterless constructor is the explicit, so `S1.X` is initialized in `S1()`. In `S2`, the parameterless constructor is the default zero-init constructor so `S2.X` is initialized in `S2(int)` instead.
```csharp
struct S1
{
int X = 1;
int Y;
public S1() { } // X = 1;
public S1(int y) : this() { Y = y; }
}
struct S2
{
int X = 2;
int Y;
public S2(int y) : this() { Y = y; } // X = 2;
}
```

Clarify struct field initialization with default constructor initializer

---

proposals/csharp-8.0/ranges.md

Spec refers to non existent type.

fix: special type implementation for array

---

proposals/improved-interpolated-strings.md

Spec side of https://github.com/dotnet/roslyn/issues/54703.

Specify unescaping rules for interpolated strings

---

proposals/lambda-improvements.md

I was looking for the status of naturally typed lambdas and couldn't find. Then Fred gave me a link to a meeting which, I assume, should be mentioned in the lambda improvements proposal too, since it touches them.

A meeting with lambda improvements mentioned

---

proposals/generic-attributes.md

Add generic attributes proposal

---

proposals/csharp-10.0/GlobalUsingDirective.md
proposals/csharp-10.0/constant_interpolated_strings.md
proposals/csharp-10.0/file-scoped-namespaces.md
proposals/csharp-10.0/improved-definite-assignment.md
proposals/csharp-10.0/record-structs.md
proposals/csharp-7.0/task-types.md
proposals/csharp-9.0/extending-partial-methods.md

Most of the fixes are updating links to sections of the spec so that they work correctly.
Other fixes include semantic markdown:
- exactly 1 H1 heading in each file.
- ATX style headers.
Discovered while working on dotnet/docs#25504

fix build warnings in docs

---

proposals/csharp-10.0/constant_interpolated_strings.md
proposals/csharp-10.0/improved-definite-assignment.md
proposals/csharp-10.0/improved-interpolated-strings.md

A few links to the standard did not include the folder path.
These were missed in #5018

fix missing links

---

proposals/csharp-7.2/span-safety.md

The compiler excludes receivers from the "Must Arguments Must Match"
rules when the type is a `readonly struct`. This exclusion was not
covered in the rules.

Clarify span safety rules for readonly receivers

---

proposals/csharp-9.0/records.md

Fixes #5186
Clarify that a matching member prevents the synthesis of that member, not all synthesized members.

Clarify matching members prevents synthesized members

---

proposals/low-level-struct-improvements.md

Feedback on discord pointed out that there were a few mistakes in the
doc:
- Use `ref field = ref value` instead of `field = ref value`j`. The
latter is correct here because it mimics how `ref` locals work
- Use `readonly ref` to describe `ref` fields that can't be reassigned
instead of `ref readonly`

Fix a couple of issues

---

meetings/2021/LDM-2021-09-20.md

`Expression<D>` was not displayed correctly without back quotes.

Correct formatting of generic type name in LDM notes

---

proposals/csharp-10.0/lambda-improvements.md

Relates to PR https://github.com/dotnet/roslyn/pull/56534

Lambda improvements: include 'Explicit return type inference' spec section

---

proposals/csharp-7.1/async-main.md
proposals/csharp-7.1/generics-pattern-match.md
proposals/csharp-7.1/target-typed-default.md
proposals/csharp-7.2/private-protected.md
proposals/csharp-7.2/readonly-ref.md
proposals/csharp-8.0/async-streams.md
proposals/csharp-8.0/default-interface-methods.md
proposals/csharp-8.0/null-coalescing-assignment.md

Fixes https://github.com/dotnet/docs/issues/26288.
These task lists were often outdated, I don't think they are tracking anything useful and they didn't render quite right on docs.MS, so I think it makes sense to delete them.
In a couple of cases, this also deletes links to documentation in `roslyn/docs/features`. If these should be preserved, I can add them back.
Also note that this PR only changes proposal that are shown on docs.MS (i.e. those under `proposals/csharp-x.y`). Those directly under `proposals` and those under `proposals/rejected` are left unchanged.

Deleted confusing task lists from proposals

---

proposals/pattern-variables.md

Championed issue: https://github.com/dotnet/csharplang/issues/4018
Prototype: https://github.com/dotnet/roslyn/compare/main...alrz:pattern-variables
Proposal: [Rendered](https://github.com/alrz/csharplang/blob/patch-4/proposals/pattern-variables.md)

Add pattern-variables.md

---

proposals/csharp-10.0/lambda-improvements.md

Making the links to the spec relative links, so they'll resolve correctly both in this repo, and when published on docs.microsoft.com
(The latest change doesn't have the folder as part of it.)

Update links to spec

---

proposals/csharp-8.0/ranges.md

This is a follow up on an LDM decision, see https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-11-01.md for more information.

Explicitly specify the order of evaluation for implicit Index/Range support

---

proposals/csharp-10.0/lambda-improvements.md

Various updates to proposals/csharp-10.0/lambda-improvements.md to match language design decisions and C#10 implementation:
- Include anonymous methods in function types and conversions (email discussion)
- Remove direct invocation
- `var` cannot be used as an explicit return type (see [2021-06-02](https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-06-02.md#conclusion))
- No inferred type for discard assignment
- Function type conversions are not standard conversions and are ignored for user-defined conversions (email discussion)
- Update better function member and better conversion from expression (see [2021-09-20](https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-09-20.md#conclusion))
- Warning implicitly converting method group to `object` (see …

Update lambda-improvements.md to match language design decisions

---

proposals/self-constraint.md

This adds a proposal for the self-constraint taking into account the feedback given on the initial draft: https://github.com/tannergooding/csharplang/commit/121b340a097552a32a3c3ad3b012d89735d1372d
[summary]: #summary
A single generic type parameter on a given interface declaration can be specified to be the `self type` and the corresponding type argument must be a type that implements the interface. In addition, a type implementing any constructed form of the interface directly (not through its base class), must use itself as a type argument for the self type type parameter in that constructed form.
[motivation]: #motivation
When dealing with static abstracts in interfaces for operator declarations, the interface must currently declare one of the generic type parameters to have a …

Adding a proposal for the self-constraint

---

proposals/csharp-10.0/caller-argument-expression.md

Relates to https://github.com/dotnet/roslyn/issues/52745
@Youssef1313 @jcouv ptal.

Clarify conversion rules for CallerArgumentExpression

---

proposals/list-patterns.md

Related to https://github.com/dotnet/roslyn/issues/57825

Standardize list pattern lowering on `Index` constructor.

---

proposals/csharp-10.0/parameterless-struct-constructors.md
proposals/csharp-10.0/record-structs.md

In a `record struct` with a primary constructor, explicit constructors require a `this()` initializer that invokes the primary constructor or _another explicitly declared constructor_.

'record struct' constructor requires 'this' initializer that calls primary constructor or explicit constructor

---

meetings/2022/README.md
proposals/required-members.md

Adds some additional details on various topics, including OHI and metadata. Also adds new questions for LDM to address in a full session in early Jan.
Relates to test plan https://github.com/dotnet/roslyn/issues/57046

Update the required members spec

---

proposals/param-nullchecking.md

Related to dotnet/roslyn#36024

Mention async methods in param-nullchecking spec

---

proposals/csharp-7.2/span-safety.md
proposals/low-level-struct-improvements.md

Updates to the low level struct improvements document. Changes:
1. Tried to put the compat issue up front. Want readers to understand that as a separate concept as it comes up many times in the feature design
2. Solved the issue of how non-constructors could return `ref struct` which had `ref` fields
3. Have firm rules now about which life time annotations we will support and how they interact with the existing rules

Low level struct updates

---

proposals/low-level-struct-improvements.md

Two updates here
- Link to an existing related discussion
- Remove a section on why ref fields can't be a new scope value. This
was an idea I had when originally working on the proposal that I
eventually discarded because it didn't work. I included it because I
wanted to let readers see alternate approaches and what flaws they had.
That particular idea was bad though and attempting to explain how it
would've worked is hard (cause it was a bad idea). Removing as it was
causing confusion in readers.

Update low level struct proposal

---

proposals/csharp-10.0/record-structs.md

Update `record struct` documentation to indicate the parameter list is optional and may be empty.

Allow optional and empty parameter list

---

proposals/csharp-10.0/improved-interpolated-strings.md

Followup from https://github.com/dotnet/roslyn/pull/57780.
Relates to test plan https://github.com/dotnet/roslyn/issues/51499

Added notes about interpolated strings in nullable flow analysis

---

proposals/csharp-9.0/native-integers.md

Update proposals/csharp-9.0/native-integers.md to indicate that native integers are not supported as `enum` base types.
Allowing native integer base types is tracked by https://github.com/dotnet/roslyn/issues/44110.
Relates to test plan https://github.com/dotnet/roslyn/issues/38821

Document native integers not supported as 'enum' base type

---

proposals/param-nullchecking.md

@RikkiGibson for review. I think that code sample was intended to have a `!!`.
@KathleenDollard FYI

Add missing `!!` in sample

---

proposals/csharp-8.0/async-streams.md

Relates to https://github.com/dotnet/roslyn/pull/60022

Clarify binding rules for `await foreach`

---

proposals/csharp-7.2/span-safety.md
proposals/low-level-struct-improvements.md
proposals/todo.txt

This update has two main parts:
- Move `[RefFieldsEscape]` from annotating methods to annotating the actual `ref` parameter that escapes. Initially this was done at the method level to remove some complexity from the rules. In reality though it's the individual parameters that matter and the correct decision is to annotate them. That gives the maximum flexibility to API designers.
- Significantly expand on the **Breaking Compatibility** section. In several one off discussions and [C# LDM meetings](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-02-28.md#conclusion-2) there was significant support for limited compat breaks to simplify this feature. Correspondingly this section was updated to have a more detailed design of what a compat break would look like and how it …

Update ref field proposal

---

proposals/csharp-10.0/improved-interpolated-strings.md

fix typo in improved-interpolated-strings.md

---

proposals/required-members.md

Update enforcement, remove outdated grammar, and correct namespaces for `SetsRequiredMembers`.

Update required members sections

---

proposals/csharp-9.0/native-integers.md

We've reviewed this PR with @cston and @tannergooding. Our conclusion is that the roslyn implementation is correct, except for:
- the `nuint -> double` and `nuint -> float` cases (https://github.com/dotnet/roslyn/issues/60714)
- `nuint->nint` (https://github.com/dotnet/roslyn/issues/60944)

Capture implemented native int conversions

---

proposals/csharp-10.0/caller-argument-expression.md

Remove gender specific pronoun from caller-argument-expression.md

---

proposals/numeric-intptr.md

Test plan https://github.com/dotnet/roslyn/issues/60578

Spec out numeric IntPtr

---

proposals/numeric-intptr.md

@cston @tannergooding for review.
Closes https://github.com/dotnet/csharplang/issues/4385

Tweak numeric IntPtr spec

---

proposals/low-level-struct-improvements.md

I'm fairly sure `<>` isn't valid C# syntax anywhere, but I might've just missed something

Fix typos in low level struct improvements

---

proposals/file-local-types.md
proposals/file-types.md

Related to dotnet/roslyn#60819

Add speclet for file-local types

---

proposals/low-level-struct-improvements.md

Relates to https://github.com/dotnet/roslyn/issues/62120

Spec `ref` in object initializers

---

proposals/low-level-struct-improvements.md

While reading through the "violating scoped" section, I noticed that it (presumably accidentally) suggests a workaround that contains a GC hole, as it attempts to roundtrip a `ref` through an unmanaged pointer in order to get around span safety rules.
It appears that ultimately the decision was made to go through with one of the other considerations instead (changing `Unsafe.AsRef` to use `scoped`), so this PR simply removes the section containing the GC hole in the hopes that it will prevent future readers from copying it.

Remove GC hole from `low-level-struct-improvements.md`

---

proposals/static-abstracts-in-interfaces.md

We want to block this for C# 11, so that a future version of C# can call the appropriate APIs on `INumberBase` and make this scenario work as expected.

Spec forbidding constant numeric patterns on `INumberBase<T>`

---

proposals/lambda-method-group-defaults.md

Championed Issue: #6051. This is a draft for a proposal to add default parameters to lambda functions and method groups, based heavily on the description in the championed issue. This topic has been discussed several times, but the proposal has yet to be merged.

Add lambda/method group defaults proposal

---

proposals/low-level-struct-improvements.md

Updates based on our deployment experiences

ref fields updates

---

proposals/low-level-struct-improvements.md

Relates to issue https://github.com/dotnet/roslyn/issues/62838

Rename `LifetimeAnnotationAttribute` to `ScopedRefAttribute` and remove unnecessary members

---

proposals/low-level-struct-improvements.md

Add a module-level `RefSafetyRulesAttribute` to indicate the scope of unannotated parameters within the module.
_Proposed by @jaredpar._

Add RefSafetyRulesAttribute for interop with existing assemblies

---

proposals/low-level-struct-improvements.md

Use `out scoped` rather than `scoped out` since `scoped` applies to the value in the calling method rather than the reference in the method being called.

Update syntax for `out scoped` variable declaration

---

proposals/low-level-struct-improvements.md

Relevant background: https://github.com/dotnet/csharpstandard/blob/standard-v6/standard/unsafe-code.md
Relates to https://github.com/dotnet/runtime/issues/73850

Relax some rules in unsafe context

---

proposals/low-level-struct-improvements.md

This allows for more natural use of `[UnscopedRef]` when applied to a `ref` of a `ref struct`
Motivating issues
- https://github.com/dotnet/roslyn/issues/63526

Separate return scopes

---

proposals/csharp-11.0/file-local-types.md
proposals/csharp-11.0/numeric-intptr.md
proposals/csharp-11.0/required-members.md
proposals/csharp-11.0/static-abstracts-in-interfaces.md

Address issues causing build warnings in dotnet/docs#31463 (Publish C# 11 speclet to docs)
There are no semantic changes to the specs.

Fix Markdown syntax

---

proposals/low-level-struct-improvements.md

Considering how the spec changes would look if we went forward with `out` parameters having *safe-to-return* of *return only*
https://github.com/dotnet/roslyn/issues/64155

Spec out as return only 

---

meetings/2022/LDM-2022-10-10.md

The phrase "thing's worth" includes a possessive, as in "the worth of the thing."

Meeting notes grammar fix

---

proposals/csharp-11.0/low-level-struct-improvements.md

Couple of items:
- Clarifying the rules around ref reassignment.
- Affirming the *safe-to-escape* of non `ref struct`. This needed clarifying after the introduction of *return only*
- Affirming the cut line for features in C# 11
closes https://github.com/dotnet/roslyn/issues/64671
related https://github.com/dotnet/roslyn/issues/62618

ref fields spec updates

---

proposals/pattern-variables.md

FYI @alrz @333fred 
If we allow some type variation, we're going to have to merge types (find the best type, by eliminating tuple name differences and resolving nullability differences) and I don't see the benefit. I'll go ahead and merge for purpose of LDM discussion today.

Require types to match between pattern variable redeclarations

---

proposals/lambda-method-group-defaults.md

Relates to test plan https://github.com/dotnet/roslyn/issues/62485

Add lambda `params` proposal

---

proposals/csharp-11.0/low-level-struct-improvements.md

We should have done this at the same time as dotnet/roslyn#64414, but better late than never.
cc @cston @jaredpar @jcouv.

Define safe-to-escape inference for out vars

---

proposals/csharp-11.0/low-level-struct-improvements.md

This is how it previously rendered both in GitHub and in [docs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/low-level-struct-improvements)
Escaping the `<` so that `<T>` isn't treated as HTML tag.
Another way to fix it is to wrap `ReadOnlySpan<T>` with backticks

Fix generic parameter rendering

---

proposals/csharp-11.0/low-level-struct-improvements.md

Reverts dotnet/csharplang#6551
From email discussion with Mads and others, we're going to require lambdas to use explicit types to specify `scoped`. This will be the same as for `ref`.
Separately, we'll make a clarification to the spec that the conversion from lambda to delegate don't **exist** when `scoped` differs in incompatible ways (as opposed to having a conversion that exists with an error reported).

Revert "Flow `scoped` in anonymous function conversion"

---

meetings/working-groups/nullability-improvements/NI-2022-10-24.md

I know our docs don't cover this use of the `!` operator. Adding that would help this situation.
After more thinking after we met, I'm thinking that might be the only necessary changes.

add comment on doc updates

---

proposals/lambda-method-group-defaults.md

Changes error to warning when lambda parameter default values or `params` modifiers differ during conversion.
Relates to https://github.com/dotnet/roslyn/pull/64961

Warn for lambda defaults/`params` differences

---

proposals/lambda-method-group-defaults.md

Implemented by https://github.com/dotnet/roslyn/pull/65300.

Clarify lambda defaults/`params` breaking change langversion

---

proposals/csharp-11.0/low-level-struct-improvements.md

Update a couple of a cases where the _ref-safe-to-escape_ of `ref` or `in` parameters was _calling method_ rather than _return only_.

Update ref-safe-to-escape of ref parameters to return only

---

proposals/csharp-11.0/low-level-struct-improvements.md

Related to dotnet/roslyn#65648
We think that because ref-struct ref-returns can only happen using ref-to-ref-struct parameters, the STE calculation should be adjusted accordingly.
There's an additional rule we want to add around STE invariance for ref expressions of ref struct type, but I want to do it in a separate spec PR and separate implementation PR.
I also added a visible section header for *method arguments must match*, because I need that phrase to be ctrl-F friendly.

Adjust invocation rules for ref return of ref struct type

---

proposals/csharp-8.0/using.md

The proposal spec'ed this out in general terms for any type, and included a provision to allow extension `Dispose` methods.
The implementation only allows `ref` struct types to use the pattern-based Dispose. Furthermore, the `Dispose` method can't be an extension method.
Fixes dotnet/docs#31815
I made edits to make the proposal match the implementation. As an alternative, I could make edits to indicate which portions of the proposal were implemented and which may be delivered in the future. Let me know which you'd prefer.

limit disposable pattern

---

proposals/csharp-9.0/init.md

Fixes dotnet/docs#32023
Fix two syntax errors in examples. The ctor for `Derived` isn't accessible. Also, remove invalid `;`.

Address docs issues in speclets

---

proposals/primary-constructors.md

See https://github.com/dotnet/csharplang/blob/main/meetings/2023/LDM-2023-01-18.md#semi-colon-bodies-for-type-declarations

Allow `class_body`, `struct_body`, `interface_body` and `enum_body` to consist of just a `;`.

---

proposals/csharp-10.0/lambda-improvements.md

I think I found a small oversight in the specification.

Fix: Remove excess brace in lambda-improvements.md

---

proposals/primary-constructors.md

Reverts dotnet/csharplang#7099

Revert "Update primary-constructors.md based on recent LDM decisions"

---

proposals/csharp-9.0/records.md

Fixes dotnet/docs#34375
While Rex was creating the draft text for the v9 standard, he noted a few suggestions for the records spec. They are detailed in the issue, and added in this PR.

Incorporate notes from drafting standard text

---

proposals/csharp-9.0/nullable-reference-types-specification.md

Fixes dotnet/docs#34381
The behavior described in the issue, and Aleksey's explanation are covered in the companion spec for the C# 9 updates for NRT. Add a link in the discussions on `class` and `class?` constraint to help readers find it.

Add links to NRT and unconstrained type params

---

proposals/csharp-11.0/low-level-struct-improvements.md

Fixes dotnet/docs#32559
Fixed sized buffers didn't make C# 11.
Also, remove the stack based linked list, as it relies on features that weren't implemented in C# 11.

Remove unimplemented struct ref features

---

proposals/csharp-11.0/low-level-struct-improvements.md

Added a section that introduces a notation for the underlying lifetime model that C# operates on. This notation is very useful when breaking down how the model works at a low level, discussing issues with the behavior and potential future features. 
As we start to look into ideas like `ref scoped`, `ref` fields to `ref struct` and similar, it will be helpful to have a shared verbiage with which to discuss it.

Lifetime annotation notation

---

proposals/csharp-9.0/nullable-reference-types-specification.md

The anchor turns into `-annotation`.

fix anchor

---

proposals/breaking-change-warnings.md

FYI @MadsTorgersen 
Those status bullets are best kept in the championed issue (easier to update) instead of the speclet.

Remove bullets from breaking-change-warnings.md speclet

---

README.md

This fixes the link to the implemention status in the roslyn repo. While on the browser you were redirected automatically to the correct branch that did not work correct on mobile.

Fix link to implemention status in Readme

---

proposals/csharp-8.0/patterns.md

The sentence:
> ...the value of *e* is **bounds**...
Should read:
> ...the value of *e* is **bound**...

Fix typo in patterns.md

---

proposals/csharp-10.0/caller-argument-expression.md

Incorrect syntax highlighting on page as the ... may have resulted in not detecting the end of function.
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/caller-argument-expression

Update caller-argument-expression.md for improved syntax highlighting

---

meetings/working-groups/collection-literals/CL-2023-05-26.md

Received feedback on ".Add" without backticks being confusing to read.

Improve wording versus referring to ".Add"

---

proposals/collection-literals.md

Add rules for *collection literal expressions* to *input type inference* and *output type inference* sections.

Collection literals: output type inferences

---

proposals/ref-readonly-parameters.md

- https://github.com/dotnet/csharplang/issues/6010
- https://github.com/dotnet/roslyn/issues/68056

Add speclet for `ref readonly` parameters

---

proposals/ref-readonly-parameters.md

Implementation: https://github.com/dotnet/roslyn/pull/68728
Relates to test plan: https://github.com/dotnet/roslyn/issues/68056

Emit `ref readonly` parameters in function pointers without `modreq(In)`

---

proposals/inline-arrays.md

Three related changes here:
1. remove `en-us` so links will resolve to the readers' locale.
1. Remove `?view=net-7.0` so API links resolve to the default view. Note that I didn't remove the query string where .NET 8 was used, as it's in preview.
1. Make absolute links to the C# standard spec language.
This PR fixes the build warnings in dotnet/docs#36277

fix docs build warnings

---

proposals/inline-arrays.md

Since this was originally written, the clauses referenced have moved. Most of that is due to the addition of patterns, but there are a couple additional clauses added as well.
See https://github.com/dotnet/csharplang/pull/7348#pullrequestreview-1534222826

fix links to spec

---

.github/ISSUE_TEMPLATE/config.yml

The new issue template page shows a link for "Propose a language idea or ask a question." When clicking that link button, GitHub shows a warning message at the top of the page stating:
> Sorry, we didn't recognize that category! Please choose one of the following valid categories.
This is because the link for the button is slightly incorrect. GitHub redirects to the correct URL, but this experience made me pause before proceeding. This PR applies the URL that GitHub redirects to so that the warning will not be shown.

Fix the new discussion link to avoid GitHub warning message

---

proposals/csharp-12.0/collection-expressions.md
proposals/csharp-12.0/inline-arrays.md
proposals/csharp-12.0/lambda-method-group-defaults.md
proposals/csharp-12.0/primary-constructors.md
proposals/csharp-12.0/ref-readonly-parameters.md
proposals/csharp-12.0/using-alias-types.md

Fix the location for the disclaimer include file for the files that moved from the parent folder into the "csharp-12.0" folder. Where that disclaimer hasn't been added, it it.
In addition, fix markdown lint issues.
Hide whitespace diff for easier review.
This will fix the docs build errors and warnings in dotnet/docs#36699

fix include, markdown lint

---

proposals/csharp-12.0/collection-expressions.md

The anchor `#constructible-collection-types` was referenced in this document, but not defined.
I think this is where it was intended to resolve.

add anchor

---

proposals/csharp-12.0/collection-expressions.md

Update overload resolution rule following [LDM-2023-08-14](https://github.com/dotnet/csharplang/blob/main/meetings/2023/LDM-2023-08-14.md).

Collection expressions: update overload resolution rule

---

proposals/csharp-12.0/collection-expressions.md

The speclet states that the builder method must be `public` and `static`.
While creating samples, I found that the actual requirement isn't `public` but rather that the builder method must be *accessible*.
This is one proposed fix. If the design intent was that builder methods must be `public`, I'll close this PR and create an issue in the roslyn repo.

Collection expressions builder method: public vs. accessible.

---

proposals/csharp-12.0/collection-expressions.md

An *output type inference* rule is not needed for spread elements since type inference considers the *iterator type* of the spread element only so there are no *output types*.

Collection expressions: remove unnecessary type inference rule

---

proposals/csharp-12.0/collection-expressions.md

Update *better conversion from expression* rule following LDM 2023-09-20.

Collection expressions: Update better conversion from expression rule

---

proposals/csharp-12.0/collection-expressions.md

Replace the collection expression conversion rule for types that implement `System.Collections.IEnumerable`, based on LDM-2023-10-02.

Collection expressions: replace conversion rule for types that implement IEnumerable

---

proposals/csharp-12.0/collection-expressions.md

See [LDM-2023-10-11.md](https://github.com/dotnet/csharplang/blob/main/meetings/2023/LDM-2023-10-11.md#conclusion)
See https://github.com/dotnet/roslyn/issues/70318

Collection expressions: prefer ReadOnlySpan<T> over Span<T> in overload resolution

---

.github/ISSUE_TEMPLATE/docs-feedback.yml

Once this is merged I'll add the config to direct customer issues to this template.
The "View file" tab on changes will give a reasonable facsimile of the experience a user will see when they are routed to this form. The fields at the bottom will be filled it.

Add docs template for spec issues

---

proposals/csharp-12.0/collection-expressions.md

Adjust type inference rules to reflect that spread elements are not expressions.

Collection expressions: spread elements are not expressions

---

proposals/csharp-12.0/experimental-attribute.md

One speclet for C# 12 didn't include the speclet disclaimer that we publish on docs.
Added it.

add speclet disclaimer

---

proposals/ref-struct-interfaces.md

This proposal sketches out what it would look like if `ref struct` were allowed to implement interfaces and participate as generic parameters.  
Related #7608

Allow ref struct to implement interfaces

---

proposals/csharp-11.0/low-level-struct-improvements.md
proposals/expand-ref.md

This proposal expands the `ref` support in the compiler to include:
1. `ref struct` as `ref` fields
2. `ref scoped` parameters and fields
3. Fully sunsetting restricted types
At the moment I'm not proposing that LDM move forward with the design. I'm still deciding if the complexity / cost is worth the gain it provides. Yet recent discussions crystalized in my mind how this would all work hence I wanted to get it written down and out for review.
The intent here is to socialize these ideas, get feedback on where this would or would not help and then make a decision on whether to push this through LDM / future .NET release.

Expanding ref support

---

proposals/csharp-12.0/primary-constructors.md

Fixes dotnet/docs#37377
The exception name was spelled incorrectly, as was the argument to the `nameof` expression

Fix type name, nameof argument in primary constructors speclet

---

proposals/csharp-11.0/low-level-struct-improvements.md

This section needs to be more explicit about what aspects of `in / ref` and `this` parameters are *return-only*. The existing language was a bit ambiguous so cleaned it up.
Discovered this when chatting with customer about the rules

Clarify return-only behavior

---

proposals/ref-struct-interfaces.md

VS Code removed whitespace at end of line, use "hide whitespace" to ignore those changes.

Add draft for demonstrating ref-struct-constraint soundness

---

proposals/csharp-12.0/collection-expressions.md

Updates following [LDM-2024-01-08](https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-01-08.md).

Collection expressions: use iteration type for convertibility of element types

---

proposals/native-lock.md

Proposal: https://github.com/dotnet/csharplang/issues/7104
[Rendered markdown](https://github.com/jjonescz/csharplang/blob/NativeLock-01/proposals/native-lock.md)

Add native lock speclet

---

meetings/2024/README.md

Add the topic for implementation specific docs in the roslyn repo.  See #7898

Add implementation specific docs

---

meetings/2024/README.md

We are making a procedural change to better manage the backlog.
I am scheduling quite a ways out and need input from everyone on the schedule: 
* Can your item be delayed past its current scheduled date? We have tough scheduling choices, so lets make sure we are prioritizing the right things.
* Do I have the correct time allotted. One item means two hours, two items are 1 hour each, and comment if you think your item is less than 1 hour?
* Will the right people be available on the scheduled date?
* If work will be blocked if we can't scheduled something earlier, comment, but with the missed meetings, there are no great answers.
* Please get links in as early as possible, definitely at least a week ahead of time.

Meetings 2024 Feb/March

---

meetings/2023/README.md
proposals/ref-out-lambda-params.md

Creates a spec for #338
This permits the simplified declaration of lambdas with parameters with modifiers, by omitting their type name.

Create spec for lambda params with modifiers without type name

---

proposals/speclet-disclaimer.md

Add details about the lifetime of these documents on Learn as it pertains to the standardization process.
Contributes to dotnet/docs#39814

refine speclet disclaimer language

---

proposals/lock-object.md

- suppress warning in object equality (`_lock != null`)

Update `Lock` object speclet

---

proposals/csharp-12.0/collection-expressions.md
proposals/params-collections.md

This PR is a proposed change allowing write-only CollectionBuilder collection types ([proposal](https://github.com/dotnet/csharplang/issues/7744)) and rephrasing the existing spec mostly in terms of *element type* instead of *iteration type*.
The plan is to review this proposal with the collection expression and params working groups, then review in LDM before merging this PR if approved.
 
Open issue: is this treated as a C# 12 bugfix or a C# 13 feature? (this affects whether we should update the C# 12 collection expression speclet)
Tagging @CyrusNajmabadi @cston @RikkiGibson @AlekseyTs for review.

Determine element type for write-only CollectionBuilder collection types

---

proposals/csharp-12.0/collection-expressions.md
proposals/params-collections.md

Previously, *collection expression conversion* required an `Add` method callable with a single argument of the *iteration type* if the collection expression has any elements. This is relaxed to an `Add` method callable with a single argument, without a requirement on the argument type.

Collection expressions: require Add method callable with a single argument for class and struct types that do not use [CollectionBuilder]

---

proposals/ref-unsafe-in-iterators-async.md
proposals/state-machine-restriction-updates.md

cc @jaredpar @AlekseyTs
[Rendered markdown](https://github.com/jjonescz/csharplang/blob/state-machine-restrictions/proposals/ref-unsafe-in-iterators-async.md)

Add proposal for "ref and unsafe in iterators and async"

---

proposals/csharp-12.0/collection-expressions.md

I'd incorrectly merged the whole change into C# 12: the change from iteration-type to element-type is fine, but the part about inferring the element-type from the `Create` method won't be handled as a C# 12 bugfix so should be taken out. It'll be re-introduced into a later speclet. 
FYI @cston @AlekseyTs @RikkiGibson

Take "non-enumerable collection types" out of C# 12

---

proposals/overload-resolution-priority.md
proposals/proposals

This is my replacement proposal for what I originally wrote up in https://github.com/dotnet/csharplang/pull/7707.

Add proposal for overload resolution priority

---

proposals/partial-properties.md

@jcouv
[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEDMACADhAJwBcoIAbbdAJmwGEBYAKAG8nt3Kd9jSL0AWbAFkAFLCLYAHtgC82AAwBKANxsOWPIRLlKg0eKmyFi7MwC+TM0A===) showing a similar partial methods scenario. In short, partial methods expect only the definition part to have default parameter values. A warning occurs when the implementation part has a default value, even if it matches the definition part.
I wasn't able to find any spec language or LDM notes which indicates that this is supposed to happen for partial methods. However, it seems to be an old behavior dating back to native compiler, which we haven't heard complaints about from generator authors etc. So, it seems reasonable to carry it over, and to help make things clear for feature development purposes, we spec a similar …

Spec behavior for default parameter values in partial properties

---

proposals/csharp-12.0/collection-expressions.md

Refer to `..e` as a spread element instead.

The `..` isn't the "spread operator"

---

proposals/partial-properties.md

Test plan: dotnet/roslyn#73090
@jcouv @333fred

Clarify caller-info behavior in partial properties/indexers

---

proposals/lock-object.md
proposals/params-collections.md

These are being published (soon) on Learn, so add the included disclaimer.
In addition, update links to the standard where the link assumed the that destination file was in the same folder.

Add the speclet disclaimer to the merged C# 13 features

---

proposals/partial-properties.md

Test plan: https://github.com/dotnet/roslyn/issues/73090
@jcouv @333fred

Spec partial properties behavior with doc comments

---

proposals/first-class-span-types.md

I think `is` pattern cannot be supported. See [ref struct interface tests](https://github.com/dotnet/roslyn/blob/a2f37e7051d904aabb3648ddaaba49f2a14eced5/src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs#L23461-L23522) for example. I assume it's not the intention to change the runtime or codegen to support this as part of the feature.

Update `is` pattern section of "first-class Span"

---

proposals/csharp-11.0/utf8-string-literals.md

Spotted some typos in UTF-8 string literals article: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/utf8-string-literals, this PR fixes typos in `utf8-string-literals.md` file.

Fix typos in utf8-string-literals.md

---

proposals/partial-properties.md

dotnet/roslyn#73090
Not attempting to change any of the weirdness detailed in here prior to feature merge. And, if any breaking changes are accepted in order to make things less weird here, we'll do them for both methods and properties.

Add spec details based on test plan review feedback

---

proposals/breaking-change-warnings.md

I believe this should be C# 12, not C# 11 where warnings would be shown.

Fix n-1 version, it is version 12, not 11

---

proposals/ref-unsafe-in-iterators-async.md

See https://github.com/dotnet/roslyn/issues/72443#issuecomment-2147915772.

Remove warning for `yield return` in `lock`

---

meetings/working-groups/roles/extension-wg-2024-06-14.md

Add notes for extensions WG 2024-06-14

---

proposals/semi-auto-properties.md

Motivated by noticing missing scenarios on SharpLab for the feature branch.
@CyrusNajmabadi indicated that this may need to go through LDM.

Add detailed design to clarify the field keyword spec and incorporate all LDM decisions

---

proposals/csharp-11.0/low-level-struct-improvements.md

This updates the ref safety rules to better explain how object initializers work.

Object initializer updates

---

proposals/extensions.md

Extract open issues and organize Expressions section

---

meetings/2024/LDM-2024-07-15-usage-data.md

The note used `a.` `b.`, which aren't recognized, and used `-` incorrectly (with >= 4 space indent), so the lists didn't display correctly

Fix lists in an LDM note

---

proposals/ref-struct-interfaces.md

Anchors in markdown should be lower case.
The previous anchor text is triggering a warning on docs.

fix anchor text

---

proposals/field-keyword.md

This content belongs in the issue, where I can easily keep all of the links related to a single topic together.

Remove ldm history from the speclet

---

proposals/field-keyword.md

A wrong line was deleted in e020a0c3bca44e52e85cbe1ce24e73913b5a38c6 when separating the sample code into two samples.

Fix definite assignment example in field keyword proposal

---

proposals/field-keyword.md

Update specification references to https://github.com/dotnet/csharpstandard/blob/standard-v7, which includes several changes including `ref` returning properties.

Field-backed properties: update references to csharpstandard v7

---

proposals/field-keyword.md

Update proposal text to reflect decision from [LDM-2022-03-02](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-03-02.md#conclusion).

Field-backed properties: initializer permitted for property with backing field

---

meetings/2024/LDM-2024-08-21.md
proposals/field-keyword.md
proposals/nullable-constructor-analysis.md

Replaces the stale Nullability section by incorporating <https://github.com/dotnet/csharplang/pull/8346> which was accepted (https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-08-21.md#field-keyword-nullability).

Incorporate the accepted field nullability proposal

---

proposals/collection-expressions-better-conversion.md
proposals/params-collections.md

The main change here is that we now require an identity conversion between element types to tiebreak among collection types.

Update the params proposal in line with the new betterness rules

---

proposals/csharp-12.0/lambda-method-group-defaults.md

Related to https://github.com/dotnet/roslyn/issues/71333.
Corresponding implementation: https://github.com/dotnet/roslyn/pull/71380
Test plan: https://github.com/dotnet/roslyn/issues/62485

Include default values and `params` modifier in method group natural type

---

proposals/csharp-7.2/readonly-ref.md

Reflecting the actual shipped behavior.
(These proposals are useful for documenting the compiler's behavior for tooling authors, or, hypothetically 🙃, someone writing unit tests that perform static analysis via reflection.)
https://sharplab.io/#v2:C4LglgNgPgAgTARgLACgYGYAE9MA1UDeqmJ2WATgKYBmmVAhgCYD2AdhAJ6ZivCYCyACgCUmALwA+TMAAW5ZgHdMrAK4QIAblQBfIA==

Fix incorrect metadata representation section for ref readonly returns

---

.github/ISSUE_TEMPLATE/proposal_template.md
Communities.md
Design-Process.md
README.md
meetings/README.md
proposals/proposal-template.md

We are revamping the process for how we communicate language design in this repo, and trying to document it better than we have in the past. The TLDR of the changes that this proposes is:
* Champion issues will be locked, and will be solely used for keeping up to date on the current status of issues.
* Instead, discussion will occur in dedicated discussions for each language feature, which will be linked from the champion issue. This will allow us to continue using threaded discussions for language features, which are a better experience.
* Language design meetings will always have checked-in documents to reference in the notes.

CSharplang process updates

---

meetings/working-groups/extensions/extension-members-unified-proposal.md

This proposal is an update on [anonymous-extension-declarations](https://github.com/dotnet/csharplang/blob/main/meetings/working-groups/extensions/anonymous-extension-declarations.md) in the following ways:
- It leans into a parameter-style syntax for specifying the receiver.
- It includes syntax for generating compatible extension methods.
- It clarifies the goals of lowering, while leaving more details to implementation.

Add unified extensions proposal

---

proposals/field-keyword.md

Simply copied from the official notes and moved to the Answered section.

Document answered questions for field keyword

---

meetings/2024/README.md

This may not be needed if we can get an approval by email. It's a bit time-sensitive as a PR in the runtime repo is blocked on this.

Queue discussion for iterator breaking change 

---

proposals/csharp-12.0/collection-expressions.md
proposals/csharp-12.0/experimental-attribute.md
proposals/csharp-12.0/inline-arrays.md
proposals/csharp-12.0/lambda-method-group-defaults.md
proposals/csharp-12.0/primary-constructors.md
proposals/csharp-12.0/ref-readonly-parameters.md

Contributes to #8098
The proposed features that weren't implemented were initializing an inline array using a collection expression, and the updated array initialization syntax as part of the inline arrays feature.
Other edits were small editorial nits, and updating anchors to the C# standard text.

Edit C# 12 speclets for features that are still proposals

---

proposals/csharp-11.0/auto-default-structs.md
proposals/csharp-11.0/checked-user-defined-operators.md
proposals/csharp-11.0/extended-nameof-scope.md
proposals/csharp-11.0/file-local-types.md
proposals/csharp-11.0/generic-attributes.md
proposals/csharp-11.0/low-level-struct-improvements.md
proposals/csharp-11.0/new-line-in-interpolation.md
proposals/csharp-11.0/numeric-intptr.md
proposals/csharp-11.0/pattern-match-span-of-char-on-string.md
proposals/csharp-11.0/raw-string-literal.md
proposals/csharp-11.0/relaxing_shift_operator_requirements.md
proposals/csharp-11.0/required-members.md
proposals/csharp-11.0/static-abstracts-in-interfaces.md
proposals/csharp-11.0/unsigned-right-shift-operator.md
proposals/csharp-11.0/utf8-string-literals.md

Contributes to #8098
- Clarify any proposed features that weren't implemented. In most cases, hide those behind `<details>` tags.
- Update all links to the C# spec from both the old Microsoft spec in csharplang and the outdated C# 7 standard from csharpstandard.
- Fix any typos as I found them.

Edit pass on C# 11 speclets

---

proposals/csharp-10.0/GlobalUsingDirective.md
proposals/csharp-10.0/caller-argument-expression.md
proposals/csharp-10.0/constant_interpolated_strings.md
proposals/csharp-10.0/file-scoped-namespaces.md
proposals/csharp-10.0/improved-definite-assignment.md
proposals/csharp-10.0/improved-interpolated-strings.md
proposals/csharp-10.0/lambda-improvements.md
proposals/csharp-10.0/parameterless-struct-constructors.md
proposals/csharp-10.0/record-structs.md

Contributes to #8098
Almost all updates were updating links to the most recent C# standard text. A couple changes involved small syntax issues in examples, such as not including `static` on an example extension method.

Edit pass on C# 10 speclets

---

meetings/working-groups/ref-improvements/ignore-overloads-in-expressions.md

Move https://github.com/dotnet/csharplang/discussions/8959 proposal to meetings/working-groups/ref-improvements/ignore-overloads-in-expressions.md.

Add ignore-overloads-in-expressions.md

---

proposals/csharp-9.0/covariant-returns.md
proposals/csharp-9.0/extending-partial-methods.md
proposals/csharp-9.0/extension-getenumerator.md
proposals/csharp-9.0/function-pointers.md
proposals/csharp-9.0/init.md
proposals/csharp-9.0/lambda-discard-parameters.md
proposals/csharp-9.0/local-function-attributes.md
proposals/csharp-9.0/native-integers.md
proposals/csharp-9.0/nullable-reference-types-specification.md
proposals/csharp-9.0/patterns3.md
proposals/csharp-9.0/records.md
proposals/csharp-9.0/target-typed-conditional-expression.md
proposals/csharp-9.0/top-level-statements.md

Review the C# 9 speclets, perform an edit pass.
Contributes to #8098
Note for reviewers:  The spec for Nullable Reference Types has mostly been incorporated into the draft v8 standard. I added links at the beginning of the speclet to point to those sections. The only feature section not in the standard yet is the `default` generic constraint.
Other changes were primarily small typos, and updating links to the referenced sections in the standard.

Edit pass on C# 9 speclets

---

proposals/field-keyword.md

Document the breaking change diagnostics that may be reported when re-compiling with the language version that includes field-backed properties.

Field-backed properties: language version diagnostics

---

proposals/first-class-span-types.md

Update *better conversion target* to prefer `ReadOnlySpan<T>` over `Span<T>`.
*Follow-up from [LDM-2024-12-04](https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-12-04.md) and  [LDM-2024-12-09](https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-12-09.md).*

Better conversion: prefer ReadOnlySpan<T> over Span<T>

---

proposals/collection-expression-arguments.md

Specify construction rules when collection arguments are included.

Collection expression arguments: collection construction

---

proposals/partial-events-and-constructors.md

Addressing @cston's feedback from https://github.com/dotnet/csharplang/pull/9059.

Improve partial events and constructors spec wording

---

meetings/2025/README.md
proposals/partial-events-and-constructors.md

This was discussed over e-mail so I think we do not need to bring it to LDM.

Move the partial constructor parsing break

---

proposals/first-class-span-types.md

That spec had moved to the csharp-13 folder.

Fix the link to ref struct interfaces

---

proposals/extensions.md

This naming convention is more consistent with existing ones (see `GeneratedNames`)

Extensions: update metadata name for extensions and rules for receiver parameter

---

meetings/working-groups/extensions/extensions-lookup.md

Relates to test plan https://github.com/dotnet/roslyn/issues/76130

Extensions: proposal to use type inference during lookup

---

proposals/field-keyword.md
proposals/fieldof.md

RuntimeHelpers.Equals is not the one-size-fits-all helper that I once thought it to be. For instance, you don't want to compare strings by reference. Otherwise, to avoid stack overflows, code that responds to PropertyChanged or sets the property begins to need to explicitly worry about whether string references are equal.

Don't promote usage of RuntimeHelpers.Equals for INPC

---

meetings/2025/README.md

Add a review of the doc specification for extension members. 
See #9133 for specification

Add extension doc review to LDM schedule

---

proposals/extensions.md

FYI @AlekseyTs @jjonescz @MadsTorgersen
Since Mads had a section on "static classes as extension containers", the naming convention I was using (ie. "extension container" for `extension(...) { ... }` blocks) didn't work. So I'm using "extension declaration" to refer to these blocks in the spec.

Extensions: clarify naming conventions, capture more open issues

---

proposals/simple-lambda-parameters-with-modifiers.md

Fix the "Syntax" anchor (it should be lower case)
Remove the `en-us` anchor so that links go to the reader's preferred language / locale.

fix anchor and remove locale information

---

proposals/partial-events-and-constructors.md

That way, global readers get their translated page.
Fixes a warning in dotnet/docs#45336

Remove the locale from the docs URL

---

proposals/ignored-directives.md

It's not part of the language spec but it's what we ended up doing in sdk, so updating the examples here to avoid confusing people that read this.

Use space as separator in ignored directives

---

proposals/extensions.md
proposals/field-keyword.md
proposals/first-class-span-types.md
proposals/null-conditional-assignment.md
proposals/partial-events-and-constructors.md
proposals/simple-lambda-parameters-with-modifiers.md
proposals/unbound-generic-types-in-nameof.md

These are the specifications that are (or will shortly be) published on Learn.
Add the disclaimer that these are the feature specification.

Add the speclet disclaimer for published specs

---

proposals/TypeUnions.md

Comma-separated `(int, short)` would be a `ValueTuple` so I'm assuming this is just a typo :)

Fix typo suggesting ValueTuple syntax for Unions

---

meetings/working-groups/extensions/Extension-API-docs.md

Recent decisions in LDM and dotnet/roslyn#78365 change how XML output is generated and should be consumed.

Update docs output for extensions

---

proposals/user-defined-compound-assignment.md

The name collision between static and instance `++`/`--` operators creates a complication for extensions operators feature. Specifically static and instance versions of the extension operators cannot be declared in the same class because of that. For example, see https://github.com/dotnet/roslyn/blob/d39b67f3bbf0b5909add4ae09a1e0aa348a32c70/src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionOperatorsTests.cs#L626

Update `++`/`--` predefined operator names in user-defined-compound-assignment.md

---

proposals/collection-expression-arguments.md

Use projections of builder methods that contain the first N-1 parameters only, so that *applicable function member* can be used unchanged.
Also update *Empty argument lists* question to match latest discussion.

Collection arguments: use projections of builder candidate methods

---

proposals/extensions.md

In terms of spec updates:
- remove indexer for now (full support may not make it in .NET 10)
- disallow `[ModuleInitializer]`
- allow `extern`
- add rule for entrypoints
- add proposal for cref
- relax inferrability rule
- mark skeleton types with `specialname`

Extensions: spec updates and track more open issues

---

meetings/2025/README.md
proposals/type-parameter-inference-from-constraints.md

Adds a championed proposal for inferring type parameters from constraints.

Infer type parameters from constraints

---

meetings/working-groups/discriminated-unions/Closed Hierarchies.md

The purpose of a `closed` class is that it can be "exhausted" by a finite list of direct base classes. However, the current spec leaves a hole where a derived class can add a type parameter that is not passed to the base class. That means the base class cannot be exhausted.
This proposal closes the hole by requiring all type parameters of derived classes to be used in the base class specification.

Add type parameter restriction to Closed Hierarchies.md

---

proposals/csharp-9.0/top-level-statements.md

Implementation: https://github.com/dotnet/roslyn/pull/79577
Motivation: https://github.com/dotnet/csharplang/discussions/9544

Allow using `/main` with top-level statements

---

meetings/working-groups/discriminated-unions/brace-syntax.md

Updated wording for clarity and consistency in the document regarding simple name declarations and type references.

Clarify language on simple name declarations and references

---

proposals/unsigned-sizeof.md

Issue: https://github.com/dotnet/csharplang/issues/9633

Add proposal for unsigned sizeof

---

proposals/collection-expression-arguments.md

Updating the collection-expression-arguments spec with the final conclusions of the LDM.
Chuck had incorporated all feedback up through LDM https://github.com/dotnet/csharplang/blob/main/meetings/2025/LDM-2025-05-12.md#constructor-binding-behavior in PR https://github.com/dotnet/csharplang/pull/9381.
However, the conclusions in that same LDM (https://github.com/dotnet/csharplang/blob/main/meetings/2025/LDM-2025-05-12.md#empty-argument-lists) about `with()` expressions were not incorporated into the spec yet. 
Updating accordingly.

Revise 'with()' usage in collection expressions
